### ISSUE TITLE
 ERROR  The 'request' argument must be string. Received type undefined

### ISSUE THREAD

**Issue by davision** [nuxt/typescript#102]
**Describe the bug**
I have updated my Nuxt v2.8 to 2.9.2 with new @nuxt/typescript-build and now I cannot get it working. Getting the same error every time I build or run a project in dev:

```
 ERROR  The 'request' argument must be string. Received type undefined                                                                                       15:05:40

  at node_modules/esm/esm.js:1:224803
  at Object.<anonymous> (node_modules/esm/esm.js:1:251922)
  at Object.t (node_modules/esm/esm.js:1:279775)
  at n (node_modules/esm/esm.js:1:279589)
  at WebpackBundler.extendBuild (node_modules/@nuxt/typescript-build/lib/module.js:53:42)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1811:17)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1813:27)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4731:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4761:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4917:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5194:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5201:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5590:30)
```

**Screenshots**
This is my nuxt.config.js:

```
export default {
  mode: 'spa',
  router: {
    linkActiveClass: 'active',
    linkExactActiveClass: 'exact-active',
    middleware: [
      'auth',
      'redirect',
    ],
  },
  plugins: [
    { src: '~plugins/vue-select', ssr: false },
    { src: '~plugins/vue-anime', ssr: false },
    { src: '~plugins/common-ui' },
    { src: '~plugins/vue-gravatar' },
    { src: '~plugins/vee-validate' },
    { src: '~plugins/vue-date' },
    { src: '~plugins/const' },
    { src: '~plugins/user' },
    { src: '~plugins/vue-js-modal' },
  ],
  styleResources: {
    scss: [
      './assets/styles/components/_mixins.scss',
    ],
  },
  css: [
    './assets/styles/vendor/grid',
  ],
  modules: [
    '@nuxtjs/axios',
    '@nuxtjs/toast',
    '@nuxtjs/style-resources',
    '@nuxtjs/auth',
  ],
  buildModules: ['@nuxt/typescript-build'],
  axios: {
    headers: { 'content-type': 'application/json' },
    baseURL: 'http://localhost:4444',
  },
};
```

My package.json: 

```
{
  "name": "app-ui",
  "version": "1.0.0",
  "description": "user interface",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/toast": "^3.2.1",
    "date-fns": "^2.0.1",
    "nuxt": "^2.9.2",
    "vue-animejs": "^2.1.1",
    "vue-click-outside": "^1.0.7",
    "vue-gravatar": "^1.3.0",
    "vue-js-modal": "^1.3.31",
    "vue-select": "^3.1.0"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^0.2.1",
    "@nuxtjs/auth": "^4.8.1",
    "@nuxtjs/axios": "^5.6.0",
    "@nuxtjs/style-resources": "^1.0.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.3.1",
    "sass-resources-loader": "^2.0.1",
    "ts-node": "^8.3.0",
    "tslint": "^5.19.0",
    "vee-validate": "^2.2.15",
  }
}

```

tsconfig.json is the same as in your repository example.

**Additional context**

**Comment by kevinmarrec** [comment]
@davision Please provide a repository with the issue, cause unfortunately I don't know what's going on

**Comment by davision** [comment]
Looks like the package.lock.json was the issue. I've removed it and reinstalled node modules. It works fine ever after. Thanks!

**Comment by evomedia247** [comment]
> **Describe the bug**
> I have updated my Nuxt v2.8 to 2.9.2 with new @nuxt/typescript-build and now I cannot get it working. Getting the same error every time I build or run a project in dev:
> 
> ```
>  ERROR  The 'request' argument must be string. Received type undefined                                                                                       15:05:40
> 
>   at node_modules/esm/esm.js:1:224803
>   at Object.<anonymous> (node_modules/esm/esm.js:1:251922)
>   at Object.t (node_modules/esm/esm.js:1:279775)
>   at n (node_modules/esm/esm.js:1:279589)
>   at WebpackBundler.extendBuild (node_modules/@nuxt/typescript-build/lib/module.js:53:42)
>   at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1811:17)
>   at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1813:27)
>   at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4731:37)
>   at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4761:45)
>   at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4917:26)
>   at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5194:19)
>   at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5201:12)
>   at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5590:30)
> ```
> 
> **Screenshots**
> This is my nuxt.config.js:
> 
> ```
> export default {
>   mode: 'spa',
>   router: {
>     linkActiveClass: 'active',
>     linkExactActiveClass: 'exact-active',
>     middleware: [
>       'auth',
>       'redirect',
>     ],
>   },
>   plugins: [
>     { src: '~plugins/vue-select', ssr: false },
>     { src: '~plugins/vue-anime', ssr: false },
>     { src: '~plugins/common-ui' },
>     { src: '~plugins/vue-gravatar' },
>     { src: '~plugins/vee-validate' },
>     { src: '~plugins/vue-date' },
>     { src: '~plugins/const' },
>     { src: '~plugins/user' },
>     { src: '~plugins/vue-js-modal' },
>   ],
>   styleResources: {
>     scss: [
>       './assets/styles/components/_mixins.scss',
>     ],
>   },
>   css: [
>     './assets/styles/vendor/grid',
>   ],
>   modules: [
>     '@nuxtjs/axios',
>     '@nuxtjs/toast',
>     '@nuxtjs/style-resources',
>     '@nuxtjs/auth',
>   ],
>   buildModules: ['@nuxt/typescript-build'],
>   axios: {
>     headers: { 'content-type': 'application/json' },
>     baseURL: 'http://localhost:4444',
>   },
> };
> ```
> 
> My package.json:
> 
> ```
> {
>   "name": "app-ui",
>   "version": "1.0.0",
>   "description": "user interface",
>   "private": true,
>   "scripts": {
>     "dev": "nuxt",
>     "build": "nuxt build",
>     "start": "nuxt start",
>     "generate": "nuxt generate"
>   },
>   "dependencies": {
>     "@nuxtjs/toast": "^3.2.1",
>     "date-fns": "^2.0.1",
>     "nuxt": "^2.9.2",
>     "vue-animejs": "^2.1.1",
>     "vue-click-outside": "^1.0.7",
>     "vue-gravatar": "^1.3.0",
>     "vue-js-modal": "^1.3.31",
>     "vue-select": "^3.1.0"
>   },
>   "devDependencies": {
>     "@nuxt/typescript-build": "^0.2.1",
>     "@nuxtjs/auth": "^4.8.1",
>     "@nuxtjs/axios": "^5.6.0",
>     "@nuxtjs/style-resources": "^1.0.0",
>     "node-sass": "^4.12.0",
>     "sass-loader": "^7.3.1",
>     "sass-resources-loader": "^2.0.1",
>     "ts-node": "^8.3.0",
>     "tslint": "^5.19.0",
>     "vee-validate": "^2.2.15"**,**
>   }
> }
> ```
> 
> tsconfig.json is the same as in your repository example.
> 
> **Additional context**
> Add any other context about the problem here.

Remove the comma after the last dependency "vee-validate": "^2.2.15"**,** << this one

**Comment by yussan** [comment]
i have same error, 
but after delete package.lock.json , everything is ok.
