### ISSUE TITLE
ts-loader dependency

### ISSUE THREAD

**Issue by darthf1** [nuxt/typescript#104]
Hi!

I just migrated my nuxt 2.8 to 2.9 typescript build with the help of your [guide](https://typescript.nuxtjs.org/migration.html). I installed the runtime as well, since I'm using `nuxt.config.ts`.

After reload, I got the following error: `Module not found: Error: Can't resolve 'ts-loader'`. 

The guide states the text below, so my guess was that ts-node was handled by the `@nuxt/typescript-runtime` package as a dependency.

> The wrapper is a binary named nuxt-ts that registers ts-node behind the scenes before running.

I did a clean build to test, and the error remains. After I did a `yarn add ts-loader`, everything was working as it should.

So shouldn't `ts-loader` be added as a depdendency of the `@nuxt/typescript-runtime`? Or should the guide be altered stating don't forget to install ts-node as well? Or should I have had it on 2.8 already, so that's the reason its not mentioned?

**Comment by darthf1** [comment]
(Don't know why i didn't look here first. According to https://github.com/nuxt/typescript/issues/104#issue-490219841 it actually IS a dependency. So I guess the error is on my side, need to check.

**Comment by RobertWacker** [comment]
@darthf1  Please tell me a solution to this problem.

**Comment by darthf1** [comment]
Not really sure what you want from me, a lot has changed in a year.

Did you read https://typescript.nuxtjs.org/guide/setup.html?

**Comment by filipsobol** [comment]
I had this issue because I used different version of `typescript` than this package.

**Comment by windx-foobar** [comment]
> I had this issue because I used different version of `typescript` than this package.

Thank you very much. You save my life, man ^^
