### ISSUE TITLE
Recursive component don't render in prod mode

### ISSUE THREAD

**Issue by NomNes** [nuxt/typescript#109]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/NomNes/Nuxt-ts-recursive-bug](https://github.com/NomNes/Nuxt-ts-recursive-bug)

### Steps to reproduce

`npm run build`
`npm run start`
open http://localhost:3000

### What is expected ?

```
<ul>
  <li>
    item 1
    <!---->
  </li>
  <li>
    item 2
    <!---->
  </li>
  <li>
    item 3
    <ul>
      <li>
        children 1
        <!---->
      </li>
      <li>
        children 2
        <!---->
      </li>
    </ul>
  </li>
</ul>
```

### What is actually happening?

```
<ul>
  <li>
    item 1
    <!---->
  </li>
  <li>
    item 2
    <!---->
  </li>
  <li>
    item 3
    <tree items="[object Object],[object Object]"></tree>
  </li>
</ul>
```

### Additional comments?

If run `npm run dev` - all ok

-----
original: [https://cmty.app/nuxt/nuxt.js/issues/c9745](https://cmty.app/nuxt/nuxt.js/issues/c9745)

**Comment by NomNes** [comment]
hack it with:
```
const components: any = {}
@Component({
  components
})
export default class Tree extends Vue {}
components.Tree = Tree
```
:)

**Comment by kevinmarrec** [comment]
If you have an issue with class components please open issue on the official repo `vue-class-component`, doesn't seem related to Nuxt TS support.
