### ISSUE TITLE
Infinite Loop with Upgrade on Nuxt 2.9.2 and Typescript

### ISSUE THREAD

**Issue by kevcodez** [nuxt/typescript#119]
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/kevcodez/nuxtjs-infnite-loop-bug](https://github.com/kevcodez/nuxtjs-infnite-loop-bug)

### Steps to reproduce

Execute `yarn` and `yarn dev`.

Navigate to localhost:3000

### What is expected ?

A typescript service is called in the nuxtServerInit-Action. That service is injected using plugin mechanism. I expect it to just be called once when the action is called.

### What is actually happening?

The plugin gets reinitiated in an infinite loop. This results in an out of memory exception.

```

<--- Last few GCs --->

[21687:0x102812000]   111726 ms: Mark-sweep 1835.4 (2054.1) -> 1834.7 (2055.4) MB, 1708.9 / 0.1 ms  (average mu = 0.126, current mu = 0.023) allocation failure scavenge might not succeed
[21687:0x102812000]   113457 ms: Mark-sweep 1836.3 (2055.4) -> 1835.4 (2053.9) MB, 1708.6 / 0.1 ms  (average mu = 0.072, current mu = 0.013) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1009288f9]
Security context: 0x2a1b07640919 <JSObject>
    1: map [0x2a1b07651201](this=0x2a1bdd1be281 <JSArray[1]>,0x2a1b9ea0d8b9 <JSFunction (sfi = 0x2a1bf202c0b1)>)
    2: log [0x2a1bfa1c7979] [/Users/kgrueneb/otto/git/nuxt-infinte-loop/node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:3751] [bytecode=0x2a1bf202c151 offset=48](this=0x2a1bbf301e59 <Object map = 0x2a1b13eebfb9>,0x2a1bdd1be1b1 <Object map = 0x2a...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20190915.195212.21687.0.001.json
Node.js report completed
 1: 0x100078c35 node::Abort() [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 2: 0x100078db9 node::OnFatalError(char const*, char const*) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 3: 0x10016e8d7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 4: 0x10016e873 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 5: 0x1002f2605 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 6: 0x1002f3d2d v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 7: 0x1002f0ae6 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 8: 0x1002eea3c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
 9: 0x1002fa114 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
10: 0x1002fa18f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
11: 0x1002c8737 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
12: 0x1005e8f67 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
13: 0x1009288f9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
14: 0x1009449fc Builtins_ArrayMap [/Users/kgrueneb/.nvm/versions/node/v12.10.0/bin/node]
error Command failed with signal "SIGABRT".
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9776">#c9776</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@kevcodez Cloned and tried your repository, I'm not able to reproduce the issue.
Unless the types errors, the compilation succeeds & I can see `hello` in browser without JS errors.

**Comment by kevcodez** [comment]
@kevinmarrec Which version of node are you running?

**Comment by kevinmarrec** [comment]
@kevcodez Updated and still no issues, I'm running Node 10.16.3 (LTS)

**Comment by kevcodez** [comment]
@kevinmarrec Tried it on a colleagues laptop, running into the same infinite loop.

We are both running Mac OS Mojave 10.14.6.

Happens on NodeJS 10 and 12 (latest versions).

**Comment by kevinmarrec** [comment]
I'm using Linux, Ubuntu 19.04.

I think you're issue is quite common, on Mac OS there is some maximum RAM allowed for programs that is not really high by default. So you may want to look at more global Mac OS issue first.

Nuxt TypeScript support enables a type checker which run with 2GB ram by default, it can be configured through [**`typeCheck`**](https://typescript.nuxtjs.org/guide/setup.html#typecheck) module option.

**Comment by kevcodez** [comment]
@kevinmarrec The option does not change the behaviour, neither enabling nor disabling it. The issue seems to be that the plugin gets instantiated in an endless loop. The console log entry from the plugin is printed > 3000 times before running out of memory.

Will message again once I tried on a windows laptop.

**Comment by kevcodez** [comment]
Also, it does work when I am using `yarn build` followed by `yarn start`. The endless loop only occurs using `yarn dev`.

**Comment by kevinmarrec** [comment]
Really weird, did you try pruning your node_modules/yarn.lock ? May be a fucked up dependency somehow ?

On my computer, plugin is only printed once on the server by page call.

**Comment by kevcodez** [comment]
Are you also running `yarn dev`? Pruning the yarn.lock didn't help. Still waiting for the colleague using windows to get here :D

**Comment by kevinmarrec** [comment]
@kevcodez Yes. `git clone`, `yarn` & `yarn dev`

**Comment by pimlie** [comment]
@kevcodez It seems your reproduction is introducing an issue in itself as axios calls `/` recursively. So what happens is that you browse to `/` then axios requests `/` which then again requests `/` which then again requests `/` which then again requests `/` which then again requests `/` which then again requests `/` which then again requests `/` which then again requests `/` which then again requests `/` etc

If you add a hook on `vue-renderer:ssr:prepareContext` then you can see this behaviour

**Comment by kevcodez** [comment]
@kevinmarrec It does work in Windows.

@pimlie So I need to not call the server (any path) during nuxtServerInit to avoid being in this loop? I can probably work around this by moving the calls to some components.

**Comment by kevinmarrec** [comment]
@kevcodez Seems reproducible now, I was on a different port than 3000 cause my 3000 was taken.
This is consistent with @pimlie answer. The endless loop only happening in development mode is cause of targeting `localhost:3000` in development.

**Comment by pimlie** [comment]
Your reproduction doesnt seem to use `server/index.js` and also it doesnt seem to contain any proxy.

It might be that your original issue stil exists, or it might be that your original issue was simply also caused by a not correct functioning proxy api. Please try to verify this that axios is contacting the correct urls and is not recursively calling itself.

**Comment by kevcodez** [comment]
With nuxt-ts, how do I tell it to use my custom server/index.js that contains some express code and a proxy (the index.js is originally taken from `npx create-nuxt-app xxx` with express`).

**Comment by aldarund** [comment]
I suggest to launch your express totally separated from nuxt.

**Comment by kevcodez** [comment]
@aldarund Two separate deployments you mean? Or within that single app?

**Comment by aldarund** [comment]
I mean your express api launched separately from nuxt app. So its two separate processed that launched separately.

**Comment by kevcodez** [comment]
I'm just wondering. When creating a Nuxt App using npx (recommended approach in the docs), it lets me choose a server side framework and generates a Javascript file launching express and nuxt. I would like to understand, why I should not extend that express server with some simple proxies and endpoints and separate them.  Could you elaborate?

**Comment by kevcodez** [comment]
I got rid of express and replaced the endpoints and proxies with server middleware, the issue no longer occurs.
