### ISSUE TITLE
fix typescript-runtime does not ship @nuxt/types

### ISSUE THREAD

**Issue by hikaruna** [nuxt/typescript#125]
**Describe the bug**
- typescript-runtime does not ship @nuxt/types.
- typescript-build ship @nuxt/type
- typescript-build installing document indicates , its can --save-dev install

When using @nuxt/types by nuxt.config.ts and npm install --production, module not found error occurs.

**To Reproduce**

1. clone https://gist.github.com/hikaruna/1d91e01d479eba555dc51bf943a8f940
1. docker build . -t nuxt-ts-production --t nuxt-production
1. docker run -it --rm nuxt-ts-production

**Expected behavior**
server running.

**Screenshots**
<img width="596" alt="スクリーンショット 2019-09-22 21 18 21" src="https://user-images.githubusercontent.com/169936/65387084-8ba56180-dd7e-11e9-8243-ccfa456b2dc9.png">

**Additional context**
I think

- @nuxt/typescript-runtime optional dependent nuxt.config.ts
- nuxt.config.ts dependent @nuxt/types

So
- @nuxt/typescript-runtime should contain @nuxt/types

---

@nuxt/typescript using @nuxt/typescript-build dependency package is bad.

**Comment by kevinmarrec** [comment]
**@nuxt/typescript-runtime** now (**0.1.7**) ships **@nuxt/types**
