### ISSUE TITLE
Vuex modules are wrongly namespaced

### ISSUE THREAD

**Issue by lmanzke** [nuxt/typescript#141]
**Describe the bug**
When creating store modules with a .ts extension, the corresponding state is wrongly namespaced. The extension is normally stripped off, but it seems that the .ts extension has not been pushed into the extensions used in the following file I think: https://github.com/nuxt/nuxt.js/blob/838bacf4c396fb0bd09adf16f5b4a3f89b4c016a/packages/vue-app/template/store.js#L85.

**To Reproduce**
1. Create a nuxt app with npx create-nuxt-app
2. Follow the instructions on https://typescript.nuxtjs.org/guide/setup.html#installation
3. Create a module in the store subdirectory with a .ts extension (casual.ts)
4. Look at the vuex tab in the vue.js devtools

**Expected behavior**
The state should be under node "casual". Instead, it is called "casual.ts"

**Screenshots**
[State view](https://user-images.githubusercontent.com/7486693/66269414-661d5b00-e848-11e9-9a73-88b8612aac0a.png)

**Additional context**
I used a custom module with the following code to circumvent the issue: 

`export default function() {
  this.nuxt.options.extensions.push('ts')
}
`

However, I think it should be automatically done when migrating to typescript using the setup instructions.

**Comment by kevinmarrec** [comment]
Could you try running project with `nuxt-ts` (runtime support) just to see if it works ?
It's cause the `options.extensions` has been removed from build module and moved to runtime one as it was supposed to only have runtime purpose.

**Comment by lmanzke** [comment]
Yes, running it with nuxt-ts solves it as well.

**Comment by kevinmarrec** [comment]
Okay, pinning this as a bug, I'll fix it whenever I'll be home tomorrow

**Comment by simllll** [comment]
Also affeceted by this bug, thanks @lmanzke  for the workaround!
