### ISSUE TITLE
Change worker memory limit

### ISSUE THREAD

**Issue by JILeXanDR** [nuxt/typescript#15]
When I run `nuxt build` I see `Using 1 worker with 2048MB memory limit`
How to set limit as 512MB? My server has only 1GB RAM and it breaks the server.

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9475">#c9475</a>)</em></sub></div>

**Comment by barinali** [comment]
For others; after migrating to `@nuxt/typescript`, associated properties should be given to the module called `@nuxt/typescript-build` in the config file as below;

```
{
  ...,
  buildModules: [
    ['@nuxt/typescript-build', {
      typeCheck: {
        memoryLimit: 4096,
        workers: 2
      },
      ignoreNotFoundWarnings: false
    }]
  ]
}
```

**Comment by rikusen0335** [comment]
I report that @barinali mentioned causes twice type check (or just only showing up? idk)
![SnapCrab_NoName_2020-4-10_10-23-2_No-00](https://user-images.githubusercontent.com/19174234/78953905-4f1c3600-7b15-11ea-99b0-7cc0f60a4a9a.png)

**Comment by kevinmarrec** [comment]
@rikusen0335 If you manually setup 2 workers I think that's why you get double output.

**Comment by rikusen0335** [comment]
@kevinmarrec No it's not. If I decrease workers to 1 or just remove that option I get 2 outputs.

**Comment by kevinmarrec** [comment]
@rikusen0335 I think you have something wrong in your configuration then, the type checker is configured to only run on **Client**, it won't be run at **Server** or **Modern Client** step.

Are you using Nuxt programatically ?

**Comment by rikusen0335** [comment]
@kevinmarrec  I am very sorry, I was writing the module `@nuxt/typescript-build` twice in buildModules 😂 
Thank you for your information!
