### ISSUE TITLE
Additional Extensions not filled by @nuxt/typescript-build

### ISSUE THREAD

**Issue by b-m-f** [nuxt/typescript#154]
### Version

[v2.10.1](https://github.com/nuxt.js/releases/tag/v2.10.1)

### Reproduction link

[https://toomuchwork.com](https://toomuchwork.com)

### Steps to reproduce

- setup @nuxt/typescript-builder
- Start nuxt programatically. const nuxt = new Nuxt => new Builder(nuxt)
- https://github.com/nuxt/nuxt.js/blob/92c7f4ed249466870a477798f910c84eb1fdd18d/packages/builder/src/builder.js#L47 will be empty. Should be ['ts', 'tsx']

### What is expected ?

additionalExtensions should be  `['ts', 'tsx']`

### What is actually happening?

additionalExtensions is ` []`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9924">#c9924</a>)</em></sub></div>

**Comment by b-m-f** [comment]
Thanks. Will try it out on wednesday when I am back on the codebase. Seems like this will likely be the culprit! It did smell like an Synchronization problem :)

**Comment by b-m-f** [comment]
@kevinmarrec This was indeed the problem. Is there a place I could add some documentation for this?

**Comment by kevinmarrec** [comment]
@b-m-f I think it's related to https://github.com/nuxt/typescript/issues/139 request, i'd say new Guide section about Programmatic usage

**Comment by chanlito** [comment]
Ok, so took me like an hour to figure out why middleware wasn't picking up `.ts` files until I stumbled upon this issue.

Current solution for me is to add `additionalExtensions: ['ts']` in the `nuxt.config.js` `build` object.

I think the default option should include `.ts` files.

BTW: I'm using Nuxt programmatically.

**Comment by kevinmarrec** [comment]
Closed by #233
