### ISSUE TITLE
sh: nuxt-ts: not found when building in a Docker container

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#159]
Dockerfile:

```
FROM node:12-alpine

ENV APP_ROOT /site

RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}

RUN npm i
RUN npm run build

ENV HOST 0.0.0.0
```

When i build an image, i get an erorr: `sh: nuxt-ts: not found`

My package.json:

```
{
  "name": "serke-client",
  "version": "1.0.0",
  "description": "Serke client",
  "author": "Alexander Kim",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "start": "nuxt-ts start",
    "generate": "nuxt-ts generate",
    "lint": "eslint --ext .ts,.js,.vue ."
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/vue-fontawesome": "^0.1.7",
    "@nuxt/typescript-runtime": "^0.2.2",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/style-resources": "^1.0.0",
    "@nuxtjs/svg": "^0.1.6",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.0",
    "nuxt": "^2.0.0",
    "nuxt-fontawesome": "^0.4.0",
    "vue-property-decorator": "^8.3.0"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^0.3.2",
    "@nuxtjs/eslint-config": "^1.0.1",
    "@nuxtjs/eslint-config-typescript": "^0.1.3",
    "@nuxtjs/eslint-module": "^1.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.1.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-prettier": "^3.0.1",
    "node-sass": "^4.12.0",
    "prettier": "^1.16.4",
    "sass-loader": "^8.0.0"
  }
}
```

Locally i can build it, but within a docker container - not, what do i miss @kevinmarrec ?

**Comment by kevinmarrec** [comment]
@webcoderkz You don't seem to miss anything, could you try with `yarn` or try do debug if you correctly have `node_modules/.bin/nuxt-ts` binary ?

**Comment by webcoderkz** [comment]
Is yarn recommended manager instead of npm?

**Comment by webcoderkz** [comment]
I'll try it right now.

**Comment by kevinmarrec** [comment]
I don't have so much knowledge around Docker but seems `RUN` / `CMD` are processed differently

**Comment by webcoderkz** [comment]
Are you sure this would work with yarn? I'm going to try yarn, because using a build command to run a container is wrong.

**Comment by kevinmarrec** [comment]
Well yeah in fact it should be kind of
```
RUN npm i
RUN npm run build
CMD [ "npm", "run", "start" ]
```

**Comment by kevinmarrec** [comment]
But the thing is that your build should be kind of done before creating your docker image though
Don't have much experience

**Comment by webcoderkz** [comment]
Yeah, it should be built already. Then i just up this container via `docker-compose`

**Comment by kevinmarrec** [comment]
You can try that :
```
RUN npm i
RUN cat node_modules/.bin
```
and inspects logs

**Comment by kevinmarrec** [comment]
Overall I think you can't npm run command thorugh `RUN`
You can maybe try 
```
npm i
npm run nuxt-ts build
```

**Comment by webcoderkz** [comment]
```
Step 7/8 : RUN cat node_modules/.bin
 ---> Running in 2772d7378a28
cat: read error: Is a directory
```

it doesn't have `node_modules` directory... Something wrong with my Dockerfile?

**Comment by kevinmarrec** [comment]
@webcoderkz Lol yeah sorry my bad I meant `ls` x)

Well you now need to figure out what's going around `RUN npm run build` then :)

**Comment by webcoderkz** [comment]
`RUN node_modules/.bin/nuxt-ts build` is actually worked. But why `npm i` works and `npm run build` doesn't?

**Comment by kevinmarrec** [comment]
Did a quick search on the web and I found you again lol : https://github.com/strapi/strapi-docker/issues/125, dunno if related

Stil it just seems `npm run ...` doesn't resolve things well, maybe `yarn` would

**Comment by kevinmarrec** [comment]
@webcoderkz Try moving `ADD . ${APP_ROOT}` after dependencies installation.

**Comment by webcoderkz** [comment]
@kevinmarrec but i've deployed a vue app (vue cli) using `RUN npm run build` in a Dockerfile and it worked, wth....

**Comment by webcoderkz** [comment]
@kevinmarrec are you using VSCode?

**Comment by kevinmarrec** [comment]
@webcoderkz Yes but I didn't test anything, I just commented here without trying anything
Lol I didn't know you were running it from the editor ^^

**Comment by webcoderkz** [comment]
Now we all know, that Docker extension in WS is sucks, i just gave it a try first time, nothing beats CLI. Haven't you tried WS yourself?

**Comment by kevinmarrec** [comment]
Years ago probably yeah, but I'm really fine with VSCode :)

**Comment by kevinmarrec** [comment]
@webcoderkz Is this issue solved then ? =)

**Comment by webcoderkz** [comment]
Yeah, it's solved, it was an issue with built-in docker-java in webstorm.

**Comment by johndog1999** [comment]
in your volume section in docker-compose.yml 
add node_modules volume

example : 
volumes:
      - ./src/client:/app/client
      - /app/client/node_modules
