### ISSUE TITLE
Wrong type for ServerMiddleware

### ISSUE THREAD

**Issue by trygveaa** [nuxt/typescript#183]
**Describe the bug**
`ServerMiddleware` is defined as an alias of `RequestHandler` from `express`. However, if you try to use for example the function `req.send`, which is available according to the types, it will fail.

**To Reproduce**
1. Create this function as a serverMiddleware:
```
    (req, res) => {
      res.send('OK')
    }
```

2. Make a request to the server and observe that you get the error "res.send is not a function".

**Expected behavior**
The types should not include functions which don't exist in runtime. I'm not sure what the correct type is though, maybe `RequestListener` from `http`.

**Additional context**
Versions:
nuxt: 2.10.2
@nuxt/typescript-build: 0.3.3
@nuxt/typescript-runtime: 0.2.3

**Comment by kevinmarrec** [comment]
I would need to check where the object is initialized/altered in Nuxt core. Any help is appreciated as I'm lacking time to do so unfortunately for now.

**Comment by rchl** [comment]
Nuxt uses `connect` framework thus it should use `connect` types, in this case, something like `import('connect').HandleFunction` possibly.

But then people will have another problem as published middlewares often assume that they are run with `express` and provide own types that depend on `express` types.

I don't think there is an ideal solution to this problem. It might need a bigger discussion. For example, Nuxt might specify types to be union of `express` and `connect` types but that would give a false impression that Nuxt is 1:1 compatible with express-specific middlewares.

**Comment by kevinmarrec** [comment]
`RequestListener` doesn't feel right, as **ServerMiddlewares** should have a third param which is the `next` function.

**Comment by patarapolw** [comment]
However, `res.write` works; but it also needs `res.end`

```typescript
const configMiddleware: ServerMiddleware = (req, res, next) => {
  res.write(JSON.stringify(yaml.safeLoad(fs.readFileSync('../config.yaml', 'utf8'))))
  res.end()
}
```

**Comment by kevinmarrec** [comment]
@danielroe Any idea how to find the good type ?

**Comment by danielroe** [comment]
They are `IncomingMessage` and `ServerResponse`.

**Comment by kevinmarrec** [comment]
@danielroe 
So
```ts
type ServerMiddleware = (req: IncomingMessage, res: ServerResponse, next: any)
``` ? What about `next` function

**Comment by danielroe** [comment]
I think it is `() => void`

**Comment by danielroe** [comment]
It is `NextFunction` in `connect`: `(err?: any) => void`

**Comment by danielroe** [comment]
The whole function is `NextHandleFunction`

**Comment by kevinmarrec** [comment]
Yeah right, I think it should be `NextHandleFunction` from `connect` instead of `RequestHandler` from `express` for sure !
