### ISSUE TITLE
Typescript 3.7.x support

### ISSUE THREAD

**Issue by victorgarciaesgi** [nuxt/typescript#186]
Typescript runtime and Typescript build don't work right now

![image](https://user-images.githubusercontent.com/15092120/68391594-4f7c6380-0168-11ea-8325-cf2156fa1bb5.png)

![image](https://user-images.githubusercontent.com/15092120/68391607-560adb00-0168-11ea-83a6-15b80f1a0c30.png)

**Comment by kevinmarrec** [comment]
Duplicate of #185
