### ISSUE TITLE
Only declares and type imports are allowed inside declare module

### ISSUE THREAD

**Issue by lenvonsam** [nuxt/typescript#191]
According to the official plugins tutorial, I just copied the code block into the plugins folder, then added the plugin in nuxt.config.js and reported an error.
Version: Nuxt@2.10.2
Here is the screenshot:
![image](https://user-images.githubusercontent.com/10168476/68738993-b0051800-0622-11ea-81f4-eb1ac009daf1.png)

![image](https://user-images.githubusercontent.com/10168476/68739023-cb702300-0622-11ea-83fa-f10ac156eb90.png)

**Comment by lenvonsam** [comment]
@kevinmarrec

**Comment by georgyfarniev** [comment]
@lenvonsam try typescript 3.6 as quick workardound, I saw some issues related to nuxt and typescript 3.7. LMK if it helped you.

**Comment by kevinmarrec** [comment]
@lenvonsam Can you confirm it works with **TypeScript 3.6** ? Thanks !

**Comment by NickBolles** [comment]
Should the module type declarations be in a myPlugin.d.ts?

**Comment by danielroe** [comment]
Yes. This is a docs issue, not a build one.

**Comment by danielroe** [comment]
Though note that it is an eslint error rather than a TypeScript build error.

**Comment by kevinmarrec** [comment]
@danielroe Can the error be fixed with some `eslint` rule ? The thing is that this lint error doesn't show up with **3.6**

**Comment by danielroe** [comment]
@kevinmarrec This is not associated with an upgrade to TypeScript 3.7 as I can replicate it with 3.6.

The issue is the `babel-eslint` parser, which is installed out of the box by `create-nuxt-app`, and which has a number of problems with TypeScript. The first thing I do in any new project is replace it with the correct parser:

```bash
yarn add --dev @typescript-eslint/parser
```

... and then edit `.eslintrc.js`:
```js
module.exports = {
  ...
  parserOptions: {
    parser: "@typescript-eslint/parser"
  },
};
```

**Comment by danielroe** [comment]
[Repro](https://github.com/danielroe/nuxt-typescript-eslint-repro).

1. Clone & install deps
2. Run eslint:
   ```bash
   yarn eslint '**/*.{vue,ts,js}'
   ```
3. Fix issue by uncommenting parser in `.eslintrc.js`.
4. Re-run eslint.

**Comment by kevinmarrec** [comment]
Alright so it never really has been an issue, right ? Also there's https://github.com/nuxt/create-nuxt-app/pull/328 nearly ready that will fix it around CNA (https://github.com/nuxt/create-nuxt-app/pull/328/files#diff-9fd823e96cf162b0ef4dd75d806e4c4eR12)

Can we close this then ?

**Comment by danielroe** [comment]
Agreed. Yes, this can be closed.
