### ISSUE TITLE
How to run with --inspect flag?

### ISSUE THREAD

**Issue by andrewvasilchuk** [nuxt/typescript#195]

**Comment by kevinmarrec** [comment]
@andrewvasilchuk Could you provide more information ? Is this some `ts-node` option ?

**Comment by andrewvasilchuk** [comment]
@kevinmarrec [Debugging](https://nodejs.org/de/docs/guides/debugging-getting-started)

**Comment by georgyfarniev** [comment]
This and many more similar questions forced me to use Nuxt programmatic API and create Koa server in the end. It's not recommended way, but easy solution for this and many other problems, such as this one: https://github.com/nuxt/typescript/issues/175

**Comment by NickBolles** [comment]
`node --inspect node_modules/.bin/nuxt-ts` seems to be working for me

**Comment by kevinmarrec** [comment]
`@nuxt/typescript-runtime` uses `ts-node` programatically, which doesn't seem to provide `inspect` support, however @NickBolles answer should indeed work.

If using Nuxt programmatically -> `ts-node --inspect src/server.ts`

**Comment by NickBolles** [comment]
FYI for future readers I had to use this with yarn 2.x
`yarn node --inspect ../../node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js dev`

This probably corresponds to something like this without yarn 2
`node --inspect ./node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js dev`

**Comment by jakiro2017** [comment]
For me this work

`NODE_ENV=dev node --inspect=6969 ./node_modules/.bin/nuxt`

**Comment by joanfabregat** [comment]
Just add `NODE_OPTIONS=--inspect` ([doc](https://nodejs.org/api/cli.html#node_optionsoptions)) to your `.env` then run Nuxt normally.
