### ISSUE TITLE
Package version for @nuxt/types should match nuxt's version

### ISSUE THREAD

**Issue by danielroe** [nuxt/typescript#199]
**Is your feature request related to a problem? Please describe.**
For people running an older version of Nuxt, it would be helpful if they could easily tell which version of `@nuxt/types` most accurately reflected the types in use in their project.

**Describe the solution you'd like**
Move `@nuxt/types` to version `2.10.2`, and then track nuxt releases.

**Comment by kevinmarrec** [comment]
@danielroe We can't do that, we'll be stuck for releasing type fixes cause Nuxt core has slower releases, it will make more people crazy than people happy ^^.

**Comment by danielroe** [comment]
@kevinmarrec Can't we do 2.10.2-0, 2.10.2-1, etc.?

**Comment by kevinmarrec** [comment]
@danielroe I'm not sure it's ideal (or even "authorized") regarding semantic versioning.
`-x` suffixes should be only used for **alpha/beta/rc** releases AFAIK.

**Comment by danielroe** [comment]
:+1:

**Comment by NickBolles** [comment]
@kevinmarrec why can't the type package match the major and minor version numbers but have a different patch version? Theoretically semantic versioning defines that there shouldn't be API changes (and hence typing changes) between patch versions.
