### ISSUE TITLE
Structure of modules in config for typescript

### ISSUE THREAD

**Issue by orblazer** [nuxt/typescript#20]
### What problem does this feature solve?

This could solve types definition for module options.

Example :
When we want load module like `@nuxtjs/dotenv` with options, we could not have types definition for that options.
In code :
```ts
import NuxtConfiguration from '@nuxt/config'

const config: NuxtConfiguration = {
  modules: [
    ['@nuxtjs/dotenv', {
      systemvars: true
    }]
  ]
}

export default config
```
Explain: With that we don't have error but we don't have types on `systemvars` and could not define that types

### What does the proposed changes look like?

For that i propose use object for modules.

With could like that :
```ts
modules: {
  '@nuxtjs/dotenv': {}, // Without options
  '@nuxtjs/dotenv': { // With options
    systemvars: true
  }
}
```

And with that on modules we could define types like :
```ts
declare module '@nuxt/config/types/module' {
  export interface NuxtConfigurationModuleOptions {
    '@nuxtjs/dotenv': {
      systemvars?: boolean
    }
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9373">#c9373</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@pi0 Any idea if this issue should be kept open ? or Should I create a specific label ?

**Comment by orblazer** [comment]
@kevinmarrec i think this could be close instead of RFC for `config/` support

**Comment by kevinmarrec** [comment]
Okay thanks @orblazer
