### ISSUE TITLE
Composition API

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#206]
Do you plan to post examples on how to use it with composition api instead of class styled components?

**Comment by NickBolles** [comment]
@webcoderkz is this what your looking for?
https://typescript.nuxtjs.org/cookbook/components/#composition-api

**Comment by kevinmarrec** [comment]
Closing issue as there's already https://typescript.nuxtjs.org/cookbook/components/#composition-api indeed and that you can find also find examples and help around https://github.com/vuejs/composition-api
