### ISSUE TITLE
Vanilla Vuex documentation

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#207]
Referring to this documentation: https://typescript.nuxtjs.org/cookbook/store.html#vanilla

How can we use modules approach?

**Comment by danielroe** [comment]
I'm happy to provide some docs on this.

@webcoderkz Could you explain a little more about what you mean?

**Comment by webcoderkz** [comment]
I mean, in the link above, there's example on using vuex in a single file, without modules. If we use modules, we have to provide typings for it, also how to use these modules inside a component Vanilla way with a TS?

**Comment by danielroe** [comment]
@webcoderkz Does #212 close this issue? Or is there still something lacking?

**Comment by webcoderkz** [comment]
@danielroe thanks, but it's missing changes to "store/index.ts" where you have to choose modules mode.

**Comment by danielroe** [comment]
@webcoderkz Not quite sure what you mean, but there's nothing else you need to do. See [Nuxt docs](https://nuxtjs.org/guide/vuex-store/).
