### ISSUE TITLE
Layout is ignored when using with vue-property-decorator

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#211]
**Describe the bug**
When using vue-property-decorator, custom layouts are being ignored.

**To Reproduce**
1. Spin up a new nuxt instance with vue-property-decorator (use class style components);
2. Create error layout in "layouts/error.vue";
3. Creat an empty layout in "layouts/empty.vue";
4. In "layouts/error.vue" component decorator use:
```
@Component({
  layout: 'empty'
})
```
5. Error page would use default layout, despite we have explicitly indicated which one to use.

**Expected behavior**
Error page would use chosen layout in layout property.

Using `layout: 'name'` does work in a component decorator, when we use it in a normal page, not error one.

https://github.com/nuxt/nuxt.js/issues/6319#issuecomment-540809239

**Comment by aldarund** [comment]
It was fixed in https://github.com/nuxt/nuxt.js/pull/6650

**Comment by kabaluyot** [comment]
<img width="1249" alt="Screen Shot 2020-11-29 at 8 48 27 PM" src="https://user-images.githubusercontent.com/38805756/100542372-78e0c380-3284-11eb-8fa5-3e0bf83e39ff.png">

Error with latest nuxt version

```
{
  "name": "daks.ts",
  "version": "1.0.0",
  "description": "A minimalistic Nuxt starter template using TypeScript, Vuetify, and Repository Pattern. Daks!",
  "author": "Karl Anthony Baluyot",
  "private": true,
  "scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "generate": "nuxt-ts generate",
    "start": "nuxt-ts start",
    "lint": "eslint --ext .ts,.js,.vue --ignore-path .gitignore .",
    "lint:fix": "eslint --ext .ts,.js,.vue --fix --ignore-path .gitignore .",
    "test:unit": "jest -- test/unit/*.spec.ts"
  },
  "lint-staged": {
    "*.{ts,js,vue}": "npm run lint",
    "*.{css,vue}": "stylelint"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@nuxt/typescript-runtime": "^2.0.0",
    "@nuxtjs/axios": "^5.11.0",
    "@nuxtjs/dotenv": "^1.4.0",
    "@nuxtjs/pwa": "^3.0.0-0",
    "@types/jest": "^26.0.15",
    "nuxt": "^2.13.0",
    "nuxt-property-decorator": "^2.7.2"
  },
  "devDependencies": {
    "@nuxt/typescript-build": "^2.0.3",
    "@nuxtjs/eslint-config-typescript": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.1",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@nuxtjs/vuetify": "^1.11.2",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-prettier": "^3.1.4",
    "husky": "^4.0.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.2.11",
    "prettier": "^2.2.1",
    "stylelint": "^13.8.0",
    "ts-jest": "^26.4.4",
    "vue-jest": "^3.0.7"
  }
}
```

**Comment by astreiko-egor** [comment]
> <img alt="Screen Shot 2020-11-29 at 8 48 27 PM" width="1249" src="https://user-images.githubusercontent.com/38805756/100542372-78e0c380-3284-11eb-8fa5-3e0bf83e39ff.png">
> 
> Error with latest nuxt version
> 
> ```
> {
>   "name": "daks.ts",
>   "version": "1.0.0",
>   "description": "A minimalistic Nuxt starter template using TypeScript, Vuetify, and Repository Pattern. Daks!",
>   "author": "Karl Anthony Baluyot",
>   "private": true,
>   "scripts": {
>     "dev": "nuxt-ts",
>     "build": "nuxt-ts build",
>     "generate": "nuxt-ts generate",
>     "start": "nuxt-ts start",
>     "lint": "eslint --ext .ts,.js,.vue --ignore-path .gitignore .",
>     "lint:fix": "eslint --ext .ts,.js,.vue --fix --ignore-path .gitignore .",
>     "test:unit": "jest -- test/unit/*.spec.ts"
>   },
>   "lint-staged": {
>     "*.{ts,js,vue}": "npm run lint",
>     "*.{css,vue}": "stylelint"
>   },
>   "husky": {
>     "hooks": {
>       "pre-commit": "lint-staged"
>     }
>   },
>   "dependencies": {
>     "@nuxt/typescript-runtime": "^2.0.0",
>     "@nuxtjs/axios": "^5.11.0",
>     "@nuxtjs/dotenv": "^1.4.0",
>     "@nuxtjs/pwa": "^3.0.0-0",
>     "@types/jest": "^26.0.15",
>     "nuxt": "^2.13.0",
>     "nuxt-property-decorator": "^2.7.2"
>   },
>   "devDependencies": {
>     "@nuxt/typescript-build": "^2.0.3",
>     "@nuxtjs/eslint-config-typescript": "^5.0.0",
>     "@nuxtjs/eslint-module": "^3.0.1",
>     "@nuxtjs/stylelint-module": "^4.0.0",
>     "@nuxtjs/vuetify": "^1.11.2",
>     "@vue/test-utils": "^1.0.0-beta.27",
>     "babel-eslint": "^10.0.1",
>     "babel-jest": "^26.6.3",
>     "eslint": "^7.14.0",
>     "eslint-config-prettier": "^6.10.0",
>     "eslint-plugin-nuxt": ">=0.4.2",
>     "eslint-plugin-prettier": "^3.1.4",
>     "husky": "^4.0.0",
>     "jest": "^26.6.3",
>     "lint-staged": "^10.2.11",
>     "prettier": "^2.2.1",
>     "stylelint": "^13.8.0",
>     "ts-jest": "^26.4.4",
>     "vue-jest": "^3.0.7"
>   }
> }
> ```

Is there a solution to this problem ?

**Comment by kabaluyot** [comment]
@astreiko-egor please take a look with this diff: https://github.com/kabaluyot/daks.ts/compare/v0.3.0...v0.6.2 

The fix for it is related to the correct versions in package.json

If you are bootstrapping a Nuxt Project with TS (and wanted a repository pattern for handling API), please take a look with https://github.com/kabaluyot/daks.ts .. Its a template for Nuxt+TS.
