### ISSUE TITLE
nuxt-ts cannot build nuxt app

### ISSUE THREAD

**Issue by smoonsf** [nuxt/typescript#214]
**Describe the bug**
after run command nuxt-ts, process hung and is not responding.

**To Reproduce**
1. Clone repository 'https://github.com/smoonsf/nuxt-ts-big'
2. Run 'yarn && yarn run dev'
3. See error

**Expected behavior**
nuxt-ts should build dev server well.

**Additional context**
I just tried to build minimal project but i cannot findout why this is not going well...

**Comment by dschewchenko** [comment]
I have the same issue from today

**Comment by smoonsf** [comment]
maybe it is related issue with this..
https://github.com/TypeStrong/ts-node/issues/918

**Comment by dschewchenko** [comment]
> maybe it is related issue with this..
> [TypeStrong/ts-node#918](https://github.com/TypeStrong/ts-node/issues/918)

Yes. I have fixed version to 8.5.2 and all works fine

**Comment by Mann-o** [comment]
Definitely a `ts-node` issue. Fixing to `8.5.2` also resolved the issue for me.

**Comment by kevinmarrec** [comment]
It was working before so I guess `ts-node` published a broken version in the meanwhile ? As I didn't publish new `runtime` version since a while.

**Comment by dschewchenko** [comment]
> It was working before so I guess `ts-node` published a broken version in the meanwhile ? As I didn't publish new `runtime` version since a while.

It's new patch version of ts-node. You just can to fix version in runtime module :)

**Comment by Mann-o** [comment]
@kevinmarrec Yes, this isn't a `@nuxtjs/typescript` issue, it's a `ts-node` issue.

**Comment by kevinmarrec** [comment]
Alright I'll close this issue (and probably also #216 ) when publishing `runtime` with last `ts-node` version, this way it will ensure no one has the buggy `ts-node` version.

**Comment by kevinmarrec** [comment]
Released new `runtime` version with last `ts-node` version.
