### ISSUE TITLE
srcDir in nuxt.config.ts has no effect

### ISSUE THREAD

**Issue by benfavre** [nuxt/typescript#218]
"srcDir" has no effect when using nuxt.config with ts extension

**Comment by kevinmarrec** [comment]
@benfavre Could you please provide a reproduction repository ? Thanks.

**Comment by benfavre** [comment]
It works, I lied
Here is me taking one of a demos to a a subfolder with the ts runtime
https://github.com/webdesign29/nuxt-ts-subfolder
