### ISSUE TITLE
Nuxt typescript. Ignore vuex *.ts files on store folder

### ISSUE THREAD

**Issue by loha** [nuxt/typescript#219]
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://github.com/loha/nuxt_2.10.2_vuex_bug](https://github.com/loha/nuxt_2.10.2_vuex_bug)

### Steps to reproduce

1. Clone github repository: https://github.com/loha/nuxt_2.10.2_vuex_bug;
2. yarn install or npm isntall;
3. yarn run dev or npm run dev.

### What is expected ?

Nuxt correctly working with *.ts and *.js files in /store folder. Vuex work correctly. Project work like in https://github.com/nuxt-community/typescript-template.

### What is actually happening?

If add in nuxt typescript project backend framework like koa.js of express.js nuxt ignore *.ts files in /store folder. Sometimes ignore *.js files too. For example, took the project https://github.com/nuxt-community/typescript-template and added the framework koa.js.

### Additional comments?

OS: Ubuntu 16.04 LTS
Node.js: v12.13.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10012">#c10012</a>)</em></sub></div>

**Comment by danielroe** [comment]
@loha Having looked at your project, it is also fixed by changing the server code to:

```js
  // The next line needs to be run in dev as well as production.
  await nuxt.ready()
  if (config.dev) {
    const builder = new Builder(nuxt)
    await builder.build()
  }
```

I think it would be worth having some documentation on this and will prepare a PR.
