### ISSUE TITLE
Docs need more info for how to set up runtime lint

### ISSUE THREAD

**Issue by crhistianramirez** [nuxt/typescript#240]
Referring to content [here](https://typescript.nuxtjs.org/guide/lint.html#runtime-lint)

The docs mention configuring the typeCheck module option but its not immediately apparent where exactly that change needs to happen. Should this be updated in `nuxt.config.js` for example? If so, where?

**Comment by kevinmarrec** [comment]
@crhistianramirez "by configuring the typeCheck **module option**" sounds relevant that it's in `nuxt.config.js`, isn't it ?
