### ISSUE TITLE
nuxt-ts --config-file=./node_modules/xxx/conifg.ts con't not running

### ISSUE THREAD

**Issue by ppzzppz** [nuxt/typescript#261]
**Describe the bug**
```sh
next-ts --config-file=./node_modules/aaa/nuxt.dev.config.ts
```
don't run config file as typescript

**Expected behavior**

![image](https://user-images.githubusercontent.com/34941345/71579605-50ae8900-2b38-11ea-9927-59adb3262576.png)

```shell
 Invalid or unexpected token                                   19:07:04

  let resolve = (dir: string) => path.join(__dirname, '..', dir)
  ^
  
  SyntaxError: Invalid or unexpected token
```

**Screenshots**
![image](https://user-images.githubusercontent.com/34941345/71579605-50ae8900-2b38-11ea-9927-59adb3262576.png)

**Additional context**

**Comment by danielroe** [comment]
@ppzzppz This is because `ts-node` won't interpret TS files located within `node_modules`.

See [this comment](https://github.com/nuxt/typescript/issues/175#issuecomment-562946731) for a response to a similar issue.

**Comment by ppzzppz** [comment]
@danielroe  thanks
