### ISSUE TITLE
Impossible to use watchQuery with vue-property-decorator

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#263]
I've tried to use `watchQuery()` inside a component decorator, but it didn't work. Is it possible to use `watchQuery()` at all? Or should i switch to a nuxt-property-decorator?

**Comment by danielroe** [comment]
@webcoderkz You should be able to use anything you can use with the Options API with decorators like so:

```ts
@Component({
  // here
  watchQuery: ['page']
})
export default class MyComponent extends Vue {
...
```

Of course, as you say, you may use `nuxt-property-decorator` which [offers a `watchQuery` hook](https://github.com/nuxt-community/nuxt-property-decorator#nuxt-hooks).

**Comment by kevinmarrec** [comment]
If `watchQuery` doesn't work without TypeScript errors, it's a Nuxt error and not related to TypeScript at all.

**Comment by webcoderkz** [comment]
@danielroe 
thanks, i've tried it in a decorator:

```
@Component({
  watchQuery(val: any) {
    console.log(val)
  }
})

```

And it didn't work.

**Comment by danielroe** [comment]
@webcoderkz As @kevinmarrec says, in that case it is most likely a problem with the property decorator or Nuxt itself. If you can provide a repro, I'll have a look, however.

**Comment by webcoderkz** [comment]
@danielroe it's just a new project with an empty component. Can you try my code above?

**Comment by webcoderkz** [comment]
Just inspected @nuxt/types/app/vue.d.ts file and found this:

```
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    watchQuery?: boolean | string[]
  }
}
```

That's why i'm getting errors, because of the type, it won't work as method:

```
watchQuery (newQuery, oldQuery) {
  return newQuery.foo && oldQuery.bar
}
```

Just like in the docs: https://nuxtjs.org/api/pages-watchquery/
