### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by shaunc** [nuxt/typescript#272]
**Describe the bug**

I have a 2.8 typescript project that I am having trouble migrating. In order to gradually introduce the various features, so as to zero-in on the problem, I cloned the "minimal" example from the website. 

running `yarn dev`, I get:

```
 ERROR  in ./pages/index.vue?vue&type=script&lang=ts&                                                                                                             friendly-errors 13:38:03

Module parse failed: Unexpected token (13:17)                                                                                                                     friendly-errors 13:38:03
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| export default Vue.extend({
|   data () {
>     const message: string = 'This is a message'
| 
|     return {
                                                                                                                                                                  friendly-errors 13:38:03
 @ ./pages/index.vue?vue&type=script&lang=ts& 1:0-117 1:133-136 1:138-252 1:138-252
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

**To Reproduce**

1. Download and unpack "minimal.zip"
2. Install locally
3. run `yarn dev`

**Expected behavior**

The example should work.

**Additional context**
```sh
% node --version
v12.6.0
% yarn --version
1.17.3
```

**Comment by kevinmarrec** [comment]
@shaunc The example is working for me locally, I can't reproduce.

```
> node -v
v12.14.1
> yarn -v
1.21.1
```

**Comment by shaunc** [comment]
Hmm... ok -- on a hunch I updated typescript and ts-node to latest (typescript 3.6.4 -> 3.7.5; ts-node now 7.0.1; not sure what it was before because updated with typescript). Now I get a different error:
```
 ERROR  Failed to compile with 1 errors                                                                                                  friendly-errors 08:41:52


 ERROR  in ./pages/index.vue                                                                                                             friendly-errors 08:41:52

Module build failed (from ./node_modules/ts-loader/index.js):                                                                            friendly-errors 08:41:52
Error: TypeScript emitted no output for /Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/t/minimal/pages/index.vue.
    at makeSourceMapAndFinish (/Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/t/minimal/node_modules/ts-loader/dist/index.js:80:15)
    at successLoader (/Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/t/minimal/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/shauncutts/src/crane/crane-serverless/packages/crane-wisdom/t/minimal/node_modules/ts-loader/dist/index.js:22:12)
                                                                                                                                         friendly-errors 08:41:52
 @ ./pages/index.vue 3:0-99 3:0-99 4:0-112 17:2-16
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```
One thought is that perhaps you should put typescript & ... into package.json as you need them.
Any ideas what other global packages might you be depending on if installed in preference to project-local copies? ts-loader? webpack? ?

**Comment by kevinmarrec** [comment]
When installing dependencies with `yarn install` or just `yarn`, it installs `@nuxt/typescript-build` :
https://github.com/nuxt/typescript/blob/renovate/fork-ts-checker-webpack-plugin-4.x/examples/options-api/minimal/package.json#L16
which itself requires `typescript` & `ts-loader`
https://github.com/nuxt/typescript/blob/renovate/fork-ts-checker-webpack-plugin-4.x/packages/typescript-build/package.json#L17

I don't know what' you're talking about cause everything works perfectly on my computer without further global installed packages :/

**Comment by shaunc** [comment]
No ... I do see the local installs. The question, I guess, is whether any of the packages will prefer to use globally installed if available over local. Indeed, minimal gives me the error message listed above.

**Comment by kevinmarrec** [comment]
@shaunc https://filebin.net/a8fwmlwofpzxsxt6/yarn.lock?t=2vhjqw03

**Comment by kevinmarrec** [comment]
Check your `node_modules` folder if the packages have been correctly installed and linked

**Comment by kevinmarrec** [comment]
Nothing should be installed as `global`, otherwise anyone would have issues when deploying to production through a CI pipeline while not having the packages installed.

**Comment by kevinmarrec** [comment]
@shaunc Also, notice that last version of TypeScript modules need **Nuxt 2.10**

**Comment by shaunc** [comment]
Thanks! ... um: so unfortunately with your yarn.lock now on first error. Indeed, I think that the change in error resulted from an experiment I tried and forgot to undo:
```
% diff ../minimal/package.json package.json
4a5,7
>   "dependencies": {
>     "nuxt": "latest"
>   },
12,15d14
<   "dependencies": {
<     "nuxt": "latest",
<     "vue-loader": "^14"
<   },
``` (ie I had tried to use previous release of vue-loader -- which got me from the original error to the error I reported, but now back to the original error.)

Note: I am using Mac OS 10.15.2 ... I have anaconda python 3.6.8 installed and linked to "python", which causes problems for fsevents build, but that is marked as optional. Could it be not optional after all?

**Comment by kevinmarrec** [comment]
Hmm, really weird. Is there any way you can test it on another machine ?

**Comment by shaunc** [comment]
My hypothesis is that it is related to fsevents problem on my Mac (about which there are several open issues... has something to do with incomplete Xcode install vs python) ... perhaps webpack fallback filesystem events also have problems on Catalina, but this is usually masked by fsevents.

It works for me in docker. In fact, I'm using [devspace](https://devspace.cloud/docs/introduction) so developing inside docker/kubernetes is not so bad. I'll close this for the moment as I think its an upstream issue; will come back in a few weeks perhaps once the community has a definitive fix for the fsevents problems. Thanks!
