### ISSUE TITLE
Bug when using property decorators?

### ISSUE THREAD

**Issue by jonthemiller** [nuxt/typescript#274]
**Describe the bug**
The package `json2typescript` does not work to notate objects within arrays, when used within a Nuxt application. This package uses object and property decorators. The decorators work as expected for primitive fields and objects not contained within arrays, but fail only for objects within arrays.

**To Reproduce**
1. Clone repository https://github.com/jonthemiller/nuxt-ts-array-deserialize
2. Run `npm install` and `npm run dev`
3. See error

**Expected behavior**
Within the `asyncData` function, an instance of `Obj` should be returned from the `JsonConvert.deserializeObject` call. It should have `items` populated and each should be an instance of the `Item` class.

**Additional context**
I first thought this was an issue with the `json2typescript` package but was able to get the expected behavior outside of Nuxt. I can provide more details or context if needed. The example repo is a very stripped down example of the issue occurring. I have currently worked around the issue by implementing a custom deserializer but would prefer to not have to do so.

**Comment by kevinmarrec** [comment]
@jonthemiller Is there a way you showcase it working outside of Nuxt ?

Overall I think it's something that can't be fix around the module, it's more likely the way how TypeScript decorators are transpiled and seems out of scope :/

**Comment by jonthemiller** [comment]
Here's a repo demonstrating json2typescript working on its own: https://github.com/jonthemiller/json2typescript-example

Yeah seems like a very weird issue only manifesting with this one use of decorators.

**Comment by kevinmarrec** [comment]
@jonthemiller Did you find a workaround ? I mean I took some time to understand what's going on but it seems to be an issue about how TypeScript decorators are handled by webpack (it passes through webpack cause you import it in a Vue file).

Did you test having both the component and the decorator file without TypeScript (just JavaScript) ?

**Comment by jonthemiller** [comment]
Yes, I do have a workaround in place in my project that is using this library. The library allows you to define a custom deserializer/serializer and we've created one that handles the array types without using the library's `[ObjectName]` notation, which bypasses the issue. We have encountered some other minor issues that I assume stem from the same bug.

That is interesting, though, I did not consider it could be Webpack causing the issue.

I just converted the files from TS to JS, removed all TS related configs and packages, and Nuxt threw the same exception. So I assume it is an issue with decorators in general going through webpack? Branch on the example repo here if you're curious: https://github.com/jonthemiller/nuxt-ts-array-deserialize/tree/no-ts

Exception:

> Fatal error in JsonConvert. Failed to map the JSON object to the class "Obj" because of a type error. Class property: items Expected type: ????? JSON property: items JSON type: object JSON value: [{"bar":"somestring"}] Cannot read property 'hasOwnProperty' of undefined

**Comment by kevinmarrec** [comment]
@jonthemiller If it results in same issue without TypeScript, it may be indeed Nuxt issue.

I think it could be worth checking with minimal VueCLI project to see if also fails, as it would mean the issue is around webpack.

Did you try to deserialize outside of `asyncData` ?

**Comment by jonthemiller** [comment]
Both the TS and JS versions work as expected in Nuxt when the logic is moved to `mounted`. I haven't tried on a vue-cli project yet. If I get some free time today I'll check that next.

**Comment by kevinmarrec** [comment]
@jonthemiller You can maybe try with `created` in SPA mode ?

Sorry I didn't have so much time to dive into it

**Comment by jonthemiller** [comment]
I still need to try it in `vue-cli` - also haven't had a lot of time to look at it either, unfortunately.

Our app needs SSR so haven't done a SPA mode build.

**Comment by jonthemiller** [comment]
I made a new vue-cli project and the code runs as expected: https://github.com/jonthemiller/vue-cli-json2typescript

Only plugins installed are typescript, eslint, and babel.

**Comment by kevinmarrec** [comment]
Seems to be closely related how `asyncData` is compiled then.

As you mentionned :
> I just converted the files from TS to JS, removed all TS related configs and packages, and Nuxt threw the same exception

It is unfortunately not related to TypeScript, so I think this issue should be handled around Nuxt repo itself directly

**Comment by jonthemiller** [comment]
Thanks for the help. I will open a bug to nuxt/nuxt.js
