### ISSUE TITLE
@nuxt/typescript-build: a build issue @^0.4.0

### ISSUE THREAD

**Issue by sketchnotes** [nuxt/typescript#282]
**Describe the bug**
In version 0.3.10 it was possible to test *.spec.ts files (jest) and build a whole application.
Since version 0.4.0 it's still possible to test files but the build fails with a bunch of errors:

**To Reproduce**
1. Clone repository 'https://github.com/sketchnotes/issue-nuxt-typescript-build'
2. Run 'yarn build'
3. See error (a full error screenshot attached):
   ERROR in /home/popov/lab/issue-nuxt-typescript-build/test/Logo.spec.ts(6,27):
6:27 No overload matches this call.
  Overload 1 of 3, '(component: VueClass<Vue>, options?: ThisTypedMountOptions<Vue> | undefined): Wrapper<Vue>', gave the following error.
    Argument of type 'VueProxy<ComponentPropsOptions<Data>, Data>' is not assignable to parameter of type 'VueClass<Vue>'.
      Type 'VueProxy<ComponentPropsOptions<Data>, Data>' is not assignable to type 'new (...args: any[]) => Vue'...

**Expected behavior**
To avoid the error:
1) Downgrade the version of @nuxt/typescript-build in package.json to the version 0.3.10
`"devDependencies": { "@nuxt/typescript-build": "^0.3.10",`
vs 
`"devDependencies": { "@nuxt/typescript-build": "^0.5.6",`
2) Run: yarn install
3) Run: yarn build

**Screenshots**
![Screenshot from 2020-01-30 23-14-49](https://user-images.githubusercontent.com/60486879/73491097-8accae00-43b6-11ea-9bae-89e9d3c7d5f6.png)

**Additional context**

**Comment by kevinmarrec** [comment]
@sketchnotes I think it has something to do with `typescript` version, did you try to maybe upgrade `@vue/test-utils` with maybe updated types ?

**Comment by kevinmarrec** [comment]
Also, you should not have `spec` (test) files handled by TypeScript when building your application, you need to excluded them in your `tsconfig.json`, and use a different `tsconfig.json` for testing purposes.

**Comment by sketchnotes** [comment]
@kevinmarrec I've updated @vue/test-utils. It did not help.

Regarding different `tsconfig.json` files - I'm afraid it will break DRY principle, only instead of code, you produce a bunch of typical files. It's also the question of further support...

After [TypeDefs for Nuxt and Builder Class #44](https://github.com/nuxt/typescript/issues/44) I try to avoid manual typescript implementation.

**Comment by kevinmarrec** [comment]
@sketchnotes The thing is that the error doesn't seem to be related to Nuxt but either how you're handling your Test **OR** how you implemented your `Logo.vue` component.

I think it should be
```ts
export default Vue.extend({
  name: 'Logo'
})
</script>
```
instead of 
```ts
import { createComponent } from '@vue/composition-api'
export default createComponent({
  name: 'Logo'
})
</script>
```

If you need the thing from `@vue/composition-api`, I think you need to upgrade it and use https://vue-composition-api-rfc.netlify.com/api.html#definecomponent `defineComponent` instead.

**Comment by sketchnotes** [comment]
@kevinmarrec I really appreciate your help. I follow [Composition API section](https://typescript.nuxtjs.org/cookbook/components/#template). Maybe I've chosen a wrong start point.

as I understand - such relevance in the different approaches is just a reasonable lack of `vue@3` integration in `nuxt`; otherwise no `@vue/composition-api` would have been needed, isn't it?

By the way, your example with `export default Vue.extend({...` works; but that, with `defineComponent`, has also some issue even if  I have the latest version of `@vue/composition-api` (now it's 0.3.4).

**Comment by kevinmarrec** [comment]
@sketchnotes For sure the change is needed as `vue/compsition-api` changed the name of the import.

For `vue@3` it's not released yet and still in development so we can't intrgrate in `nuxt` for now, but yes Composition API is **built-in** in Vue 3.

I'm gonna look at what is still making error with `defineComponent`

**Comment by kevinmarrec** [comment]
@sketchnotes Is your issue still related to testing ?

**Comment by sketchnotes** [comment]
@kevinmarrec I've checked [the updated example](https://github.com/sketchnotes/issue-referenced-during-render).
a App.vue component pretty simple:
```
<template>
  <!-- eslint-disable-next-line -->
  <div class="container" v-html="author" />
</template>

<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api'

export default defineComponent({
  setup() {
    const author = ref('&#8734;')

    return {
      author
    }
  }
})
</script>
```

The App.spec.ts is rather the same:
```
import { mount } from '@vue/test-utils'
import App from '@/components/App.vue'

describe('App', () => {
  test('is a Vue instance', () => {
    const wrapper = mount(App)
    expect(wrapper.isVueInstance()).toBeTruthy()
  })
})
```
As a result, the test passed with [Vue warn] "Property or method "author" is not defined on the instance but referenced during render."

![Screenshot from 2020-03-13 16-28-07](https://user-images.githubusercontent.com/60486879/76631079-c2984b00-6549-11ea-91a4-798870118c63.png)

there is one more, but maybe because of a recent version:
When `vue-jest` is updated to the current version (3.0.5) - there is an error during a test:
`Cannot find module 'babel-core'`

**Comment by kevinmarrec** [comment]
@sketchnotes Do you have any update or side note about this issue ?
I didn't take the time to explore solutions yet

**Comment by sketchnotes** [comment]
@kevinmarrec. It's persistent - the same testing warning while using `defineComponent`, and it's all good with Vue.extend
```
<template>
  <!-- eslint-disable-next-line -->
  <div class="container" v-html="author" />
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'Logo',
  data() {
    return {
      author: '&#8734;'
    }
  }
})
</script>
```
![Screenshot from 2020-04-09 19-55-35](https://user-images.githubusercontent.com/60486879/78920794-9e725000-7a9c-11ea-907f-655a251c1cb9.png)

**Comment by ShaggyTech** [comment]
I submitted a pull request with a fix in your example repo: https://github.com/sketchnotes/issue-nuxt-typescript-build/pull/2

This appears to be fixed by updating the following dependencies:

`@nuxt/typescript-runtime`:  `^0.3.8` => "^0.4.5`
`@vue/composition-api`:  `^0.3.4` => "^0.4.0`
`@nuxt/typescript-build`: `^0.5.6` => `^0.6.0`

**Comment by sketchnotes** [comment]
Nice! (y)

**Comment by kevinmarrec** [comment]
@ShaggyTech @sketchnotes 

FYI, latest versions are :
- @nuxt/typescript-runtime@0.4.6
- @nuxt/typescript-build@0.6.6
- @vue/composition-api@0.5.0

@sketchnotes Please close the issue if your repo is correctly fixed :)

**Comment by sketchnotes** [comment]
yeap, JIC I've checked the latest versions as well. It works. The issue is closed.

Thanks @ShaggyTech @kevinmarrec
