### ISSUE TITLE
declarations for chalk

### ISSUE THREAD

**Issue by uncleGena** [nuxt/typescript#286]
**Describe the bug**
ERROR in console
how can I remove that error?

**Screenshots**
<img width="784" alt="Screen Shot 2020-02-10 at 15 26 29" src="https://user-images.githubusercontent.com/11743243/74153976-59f04280-4c1a-11ea-9cfd-fa5040e64fde.png">

**Comment by danielroe** [comment]
@uncleGena You have an older version of chalk installed that conflicts with the version used by Nuxt.

Chalk now provides its own type definitions - see [the types package](https://www.npmjs.com/package/@types/chalk).

**Comment by uncleGena** [comment]
Yes but managing dependencies versions is npm's job. How could I break that? I searched in packages.lock file and it seems that only jest using latest version (3.0) of chalk. May be it is in my typescript config ? 
Currently I've ``` // @ts-ignore ``` that line in this file and hope It will debug itself in future ))

**Comment by rchl** [comment]
`@nuxt/cli` uses chalk and `babel` also so it can't be that the only version you have is from `jest`.

It should work if you add chalk dependency explicitly with `npm i chalk`.

(And npm or, more generally, node dependence management is not perfect so problems like that are not unlikely).
