### ISSUE TITLE
Blank project throws errors

### ISSUE THREAD

**Issue by tomturton** [nuxt/typescript#298]
## Platform
- Ubuntu 18.04.4
- Node: 12.14.1

## Steps to reproduce:
1. `npx create-nuxt-app typescript-nuxt`
    - NPM
    - Element UI
    - No server framework
    - No additional modules
    - ESLint and Lint staged files
    - Jest framework
    - SPA
    - jsconfig.json
2. `cd typescript-nuxt`
3. `npm install --save-dev @nuxt/typescript-build`
4. Add `'@nuxt/typescript-build'` to `buildModules`
5. Create _tsconfig.json_ as described by [Setup page](https://typescript.nuxtjs.org/guide/setup.html#configuration)
6. Create _vue-shim.d.ts_ as described by [Setup page](https://typescript.nuxtjs.org/guide/setup.html#configuration)
7. `npm run dev`

## Errors
```
ERROR  ERROR in /home/tom/dev/typescript-nuxt/node_modules/@nuxt/types/app/index.d.ts(119,18):
119:18 Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Type 'NuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
      Type 'DefaultNuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
        Type 'DefaultNuxtLoading' provides no match for the signature '(options: LoadingServiceOptions): ElLoadingComponent'.
    117 | }
    118 | 
  > 119 | export interface NuxtApp extends Vue {
        |                  ^
    120 |   $options: NuxtAppOptions
    121 |   $loading: NuxtLoading
    122 |   context: Context


 ERROR  ERROR in /home/tom/dev/typescript-nuxt/node_modules/@types/webpack-dev-middleware/index.d.ts(10,27):
10:27 Cannot find module 'loglevel'.
     8 | 
     9 | import * as webpack from 'webpack';
  > 10 | import * as loglevel from 'loglevel';
       |                           ^
    11 | import { NextHandleFunction } from 'connect';
    12 | import MemoryFileSystem = require('memory-fs');
    13 | 

ℹ Version: typescript 3.7.5
```

In VSCode, I notice there is also a parsing error in _vue-shim.d.ts_:
```
Parsing error: Imports within a `declare module` body must always be `import type` or `import typeof`
  1 | declare module "*.vue" {
> 2 |   import Vue from 'vue'
    |   ^
  3 |   export default Vue
  4 | }
  5 |eslint
```

## Example repo
https://github.com/tomturton/typescript-nuxt

**Comment by gainhad** [comment]
> ```
> Parsing error: Imports within a `declare module` body must always be `import type` or `import typeof`
>   1 | declare module "*.vue" {
> > 2 |   import Vue from 'vue'
>     |   ^
>   3 |   export default Vue
>   4 | }
>   5 |eslint
> ```

Also experiencing this problem. Haven't found a solution yet.

**Comment by kevinmarrec** [comment]
See https://github.com/nuxt/typescript/issues/49, it's unfortunately unfixable (unless someone find some magic)
