### ISSUE TITLE
Allow for specifying TypeScript configuration

### ISSUE THREAD

**Issue by Roms1383** [nuxt/typescript#301]
**Is your feature request related to a problem? Please describe.**
I tried to implement a project in a *micro-service / micro-frontend* way, having sourcecode for the *app part* in`./src/app` (using for example Vue.js / Nuxt.js / Vuex / Storybook) and sourcecode for the *server part* in `./src/server` (using for example Nest.js / Serverless) respectively.

Currently I can't override on the fly my `./tsconfig.json` directly in `nuxt.config.ts` (I tried different approaches, dug into the sourcecode, no matter how changes were ignored), neither was I able to directly specify the path to a different file, e.g. `./tsconfig.app.json`.

The reason why I need this is that I need to transpile them differently :
*app part*
```json
{
  "compilerOptions": {
    "rootDir": "src/app",
    "outDir": "dist",
    "target": "es2018",
    "module": "esnext",
    ...
    "types" : ["node", "@types/jest", "@nuxt/types","@nuxt/vue-app","@nuxtjs/vuetify"],
    ...
  },
  "exclude": [
    "**/*.spec.ts",
    "**/*.test.ts",
    "node_modules",
    "lib",
    "dist",
    "nuxt.config.ts",
    "src/app/**/*.stories.[tj]s"
  ]
}
```
*server part*
```json
{
  "compilerOptions": {
    "rootDir": "src/server",
    "outDir": "lib",
    "target": "es6",
    "module": "commonjs",
    ...
    "types" : ["node", "@types/jest", "@types/joi", "@types/mongoose"],
    ...
  },
  "exclude": [
    "**/*.spec.ts",
    "**/*.test.ts",
    "node_modules",
    "lib",
    "dist",
    "nuxt.config.ts",
    "src/server/seeds/**",
    "src/server/generate/**"
  ]
}
```

**Describe the solution you'd like**
IMHO `nuxt-ts` should provide the same mechanism as TypeScript already offers to override transpilation options (e.g. support for `compilerOptions`, `--project` and so on).
It should also be available without having to hook a custom Webpack configuration.

**Describe alternatives you've considered**
My current solution was to use `./tsconfig.json` for the *app part* while specifying a `tsconfig.server.json` for the *server part* (this works like a charm), but I'm not quite satisfied with it (it could actually bring more confusion in a real-world project with teams of multiple people).

**Additional context**
Not that I'm thinking of.

**Comment by kevinmarrec** [comment]
@Roms1383 Sorry if it's likely not documented, but you can try `--tsconfig [path/to/file]` : https://github.com/nuxt/typescript/blob/master/packages/typescript-runtime/src/index.ts#L7

**Comment by Roms1383** [comment]
Thanks @kevinmarrec but I've already tried and there's still some plugin / webpack thingy messin' up somewhere.

I can guess from the stacktrace that it's probably something easy to fix, but I'm just beginning with both Nuxt and Webpack  :
```sh
$ yarn nuxt-ts --tsconfig tsconfig.app.json
...                                                                                                                                                                              
 ERROR  Cannot find "/Users/*****/development/sample-project/tsconfig.json" file. Please check webpack and ForkTsCheckerWebpackPlugin configuration.

Possible errors: 
  - wrong `context` directory in webpack configuration (if `tsconfig` is not set or is a relative path in fork plugin configuration)
  - wrong `tsconfig` path in fork plugin configuration (should be a relative or absolute path)

  Possible errors:
  - wrong `context` directory in webpack configuration (if `tsconfig` is not set or is a relative path in fork plugin configuration)
  - wrong `tsconfig` path in fork plugin configuration (should be a relative or absolute path)
  at ForkTsCheckerWebpackPlugin.apply (node_modules/fork-ts-checker-webpack-plugin/lib/index.ts:294:13)
  at webpack (node_modules/webpack/lib/webpack.js:51:13)
  at compilers.webpackConfigs.map (node_modules/@nuxt/webpack/dist/webpack.js:5255:24)
  at Array.map (<anonymous>)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5254:37)
```
I went so far as to try many combos in `nuxt.config.js` and also output my webpack context to the console but I can't find the remaining setting pointing out to `tsconfig.json` yet.

**Comment by Roms1383** [comment]
Wouldn't it be related to [this](https://github.com/nuxt/typescript/blob/826234b5ff24a90e771d10b1029d1adabd8de6fb/packages/typescript-build/src/index.ts#L79) ?

**Comment by Roms1383** [comment]
Actually the error is here https://github.com/nuxt/typescript/blob/826234b5ff24a90e771d10b1029d1adabd8de6fb/packages/typescript-build/src/index.ts#L79 : the settings are not passed down to the plugin.

**Comment by Roms1383** [comment]
Switched to Bug report : [Issue with custom TypeScript file](https://github.com/nuxt/typescript/issues/306)
