### ISSUE TITLE
404 error when trying to edit a docs page

### ISSUE THREAD

**Issue by revolter** [nuxt/typescript#302]
**Describe the bug**

**To Reproduce**
1. Go to https://typescript.nuxtjs.org/examples/options-api/minimal.html
2. Click the "Edit this page on GitHub" link
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kevinmarrec** [comment]
@revolter Examples pages are autogenerated through https://github.com/nuxt/typescript/blob/master/docs/.vuepress/config.js#L193

I should try to find out if we can disabled the "Edit" links for those pages
