### ISSUE TITLE
Where to add the vue-shim.d.ts file?

### ISSUE THREAD

**Issue by revolter** [nuxt/typescript#303]
https://typescript.nuxtjs.org/guide/setup.html#configuration

> You will also need to provide types for Vue files by adding the following type declaration:

Where?

**Comment by kevinmarrec** [comment]
Root folder OR create a `@types` folder in root folder

**Comment by revolter** [comment]
And am I able to place them in a custom folder?

**Comment by kevinmarrec** [comment]
Yes but you'll need to configure `typeRoots` of `tsconfig.json` :
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

You can also probably just add `location/to/your/file` to `types` array.

**Comment by kouts** [comment]
For anyone looking for this for Nuxt 4, you can add your shim file inside `shared`, e.g.
`shared/shims/my-shim.d.ts`
