### ISSUE TITLE
Issue with custom TypeScript file

### ISSUE THREAD

**Issue by Roms1383** [nuxt/typescript#306]
**Describe the bug**
Check [this feature request](https://github.com/nuxt/typescript/issues/301) which actually is already supported via CLI argument `--tsconfig` as mentioned [here](https://github.com/nuxt/typescript/issues/301#issuecomment-593464414) and actually ends up being a minor bug.

**To Reproduce**

*platform*
Node v10.17.0

*dependencies*
"nuxt": "^2.11.0"

*devDependencies*
"@nuxt/types": "^0.6.3",
"@nuxt/typescript-build": "^0.5.8",
"@nuxt/typescript-runtime": "^0.3.10",
"ts-loader": "^6.2.1",
"ts-node": "^8.6.2",
"typescript": "^3.7.5",

`nuxt.config.ts` (shortened for simplicity)
```ts
export default {
// ...
buildModules: [
    '@nuxtjs/vuetify',
    '@nuxt/typescript-build',
  ],
}
```

**Expected behavior**
It should be able to load TypeScript config from `my-tsconfig.json` for example, instead of default `tsconfig.json`

**Additional context**
Actually what happens is that the parameters is correctly retrieved from the CLI arguments [here in typescript-runtime](https://github.com/nuxt/typescript/blob/a04b8784194d7b600dc9b9b378685d61353a61ba/packages/typescript-runtime/src/index.ts#L8) but elsewhere it then loads configuration from the default location for ForkTsCheckerWebpackPlugin here in [typescript-build](https://github.com/nuxt/typescript/blob/826234b5ff24a90e771d10b1029d1adabd8de6fb/packages/typescript-build/src/index.ts#L79)

Note : Switching `typeCheck` to **false** allows to ignore this function but it then fails while compiling with :
<img width="1440" alt="Screen Shot 2563-03-03 at 13 25 08" src="https://user-images.githubusercontent.com/21016014/75748624-864b3a80-5d52-11ea-8e11-c9a4eadc642d.png">
> NB : I removed my default `tsconfig.json`, hence this error

**Comment by Roms1383** [comment]
As a side note I'm currently trying to fix it but `ts-node` registered value can't be from its `readConfig(...)` method as it's not exported.

Meanwhile it could either :

1. read value from the `argv` as it's done in [typescript-runtime](https://github.com/nuxt/typescript/blob/a04b8784194d7b600dc9b9b378685d61353a61ba/packages/typescript-runtime/src/index.ts#L8)

1. read value from webpack config maybe (still searching for it as I'm quite new to it)

1. accept a new `tsconfig` parameter (but this is quite annoying since it would then require to be both set with `--tsconfig` CLI argument and setting in `nuxt.config.js`)

Any suggestion ?

**Comment by Roms1383** [comment]
I made it work this way :

*// @nuxt/typescript-build/index.ts
```ts
// ...
if (options.typeCheck && isClient && !isModern) {
      const ForkTsCheckerWebpackPlugin = require(this.nuxt.resolver.resolveModule('fork-ts-checker-webpack-plugin'))
      const customPath = process.argv.find((_arg, index) => index > 0 && process.argv[index - 1] === '--tsconfig')
      const tsConfigPath = path.resolve(customPath || this.options.rootDir!, customPath && customPath.endsWith('.json') ? '' : 'tsconfig.json')
      config.plugins!.push(new ForkTsCheckerWebpackPlugin(Object.assign({
        vue: true,
        tsconfig: tsConfigPath,
        formatter: 'codeframe',
        logger: consola.withScope('nuxt:typescript')
      }, options.typeCheck)))
    }
```

But it still requires `ts-loader` to be set up correctly :

*// nuxt.config.ts*
```ts
export default {
// ...
buildModules: [
    '@nuxtjs/vuetify',
    [
      '@nuxt/typescript-build',
      {
        // required on compilation
        loaders: {
          ts: { configFile: 'my-tsconfig.json' },
          tsx: { configFile: 'my-tsconfig.json' },
        }
      }
    ]
  ],
}
```

It doesn't look like a proper fix to me, but I hope this helps in understanding

**Comment by kevinmarrec** [comment]
@Roms1383 There are 2 typescript configuration by default.
- Runtime (default: tsconfig.json of rootDir **+ compilerOptions.module = "commonjs"**
- Build (default: tsconfig.json of rootDir)

The major issue is that to support runtime, i don't remember why exactly, the `module` compilerOption need to be `"commonjs"`, meanwhile build one should be `"esnext"`.

Something you may don't know :

https://github.com/nuxt/typescript/blob/master/packages/typescript-build/src/index.ts#L82
You can have `typeCheck` equal to `{ tsconfig: YOUR_CUSTOM_PATH }` in your Nuxt configuration.

So coupling --tsconfig for runtime, and tsconfig location in nuxt.config.ts, you're should be good to go, isn't it ?

**Comment by Roms1383** [comment]
@kevinmarrec I've lost the thread of it since it's a couple of weeks have passed already and I had to switch to another development, but giving it a naive try it seems indeed like it works !
