### ISSUE TITLE
The option ignoreNotFoundWarnings: true isn't working for me.

### ISSUE THREAD

**Issue by chanlito** [nuxt/typescript#310]
**Describe the bug**
I'm trying to ignore these warnings.

<img width="373" alt="Screen Shot 2020-03-09 at 8 21 08 PM" src="https://user-images.githubusercontent.com/15667259/76216620-84e2ac00-6243-11ea-9ed5-df0540325f92.png">

**Expected behavior**
When I set `ignoreNotFoundWarnings: true` to the module options, I expect it to ignore these warnings.

**My Workaround**
My current workaround is to change the regex check to the following:
```ts
{
  // ...
  build: {
    warningIgnoreFilters: [
      warn =>
        warn.name === "ModuleDependencyWarning" &&
        /export '.*'( \(reexported as '.*'\))? was not found in/.test(
          warn.message
        )
    ];
  }
  // ... 
}
```

**Comment by kevinmarrec** [comment]
@chanlito Is just changing regex 
```js
/export .* was not found in /
```
by
```js
/export '.*' was not found in /
```
works ?

It might be just the quotes that are missing

**Comment by chanlito** [comment]
@kevinmarrec I can confirm that regex should have **quotes**.

**Comment by kevinmarrec** [comment]
@chanlito `.*` in regex matches **quotes** as well so I'm not sure your error come from here

**Comment by kevinmarrec** [comment]
@chanlito Any update ? :)

**Comment by chanlito** [comment]
My project still complain without the single quotes.

**Comment by kevinmarrec** [comment]
@chanlito 
![image](https://user-images.githubusercontent.com/25272043/78252096-9a6d8d80-74f2-11ea-881c-afb15e1934a9.png)

As I said `'` should be handled as a character so it should work, you can see on my regex tester screenshot it works. So i'm wondering what is your not handled warning and why it just don't work

**Comment by kevinmarrec** [comment]
@chanlito Were you saying the regex was just lacking "reexported" check regex check ?

**Comment by chanlito** [comment]
@kevinmarrec I've upgrade all deps to latest. No longer seeing the error, so I guess it's working fine. 
Thank you for following up.
