### ISSUE TITLE
Following migration guide from new nuxt project results in inability to compile simplist component

### ISSUE THREAD

**Issue by SumNeuron** [nuxt/typescript#312]
**Describe the bug**
Seems that linting errors arise when following default setup / migartion guide

**To Reproduce**
1. Clone repository `https://gitlab.com/SumNeuron/nuxt-ts/`
2. Run `npm run dev`
3. See error

namely, that this component (following the sfc guide for class composition) fails to compile

```vue
<template>
  <div>Name: {{ name }}</div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator'

interface User {
  name: string
}


@Component 
class TSComp extends Vue {
  @Prop({ type: Object, required: true }) readonly user!: User

  message: string = 'internal data'

  get name(): string {
    return `${this.user.name}: ${this.message}`
  }
}

export default  TSComp
</script>

```

**Expected behavior**
That it works

**Additional context**

**Comment by kevinmarrec** [comment]
First you don't have a failing compilation but a successful now but with an `eslint` warning.

It's cause your **ESLint** configuration (`.eslintrc.js`) is not correctly configured.

Overall you're extending configurations that are not existing or not installed such as `@vue/typescript` or `@vue/prettier`.

I recommend you to only extend from `@nuxtjs/eslint-config-typescript` :
```js
extends: ['@nuxtjs/eslint-config-typescript']
```
Then if you need to extend other things like `prettier` configurations, ensure `@nuxtjs/eslint-config-typescript` is always the last one in the array.

Finally, you'll need to remove `parserOptions` as mentionned here : https://typescript.nuxtjs.org/guide/lint.html#configuration

**Comment by kevinmarrec** [comment]
@SumNeuron I cloned your project, and aside ESLint warnings, everything works, I used `yarn` to install dependencies. Maybe you had some broken dependencies ?

As it's not reproducible, please give update or I'll close the issue in the coming days, thanks :)

**Comment by SumNeuron** [comment]
@kevinmarrec I removed some of the default linters from nuxt's `npx create-nuxt-app` setup and then it worked. I would like to use prettier etc, and I had to change the default config to handle spaces after functions

**Comment by kevinmarrec** [comment]
Alright then your code previously was falling into this issue : https://typescript.nuxtjs.org/guide/lint.html#configuration (Warning section)

Closing for now

Using Eslint + Prettier for TypeScript is hell, you can ask on Discord TypeScript there's maybe someone who succeeded to setup it correctly.
