### ISSUE TITLE
Cannot load *.ts files as part of Vuex store

### ISSUE THREAD

**Issue by afontcu** [nuxt/typescript#320]
**Describe the bug**
A nuxt project with `@nuxt/typescript-build` doesn't seem to load `*.ts` files in `/store`.

**To Reproduce**
1. Set up a new nuxt+ts project using `create-nuxt-app`
2. Create some store modules in `*.ts` files (even used [the one from the docs](https://typescript.nuxtjs.org/cookbook/store.html#basic-typing)).
3. See the module not being loaded (not in the template, not in devtools)
4. Change the file extension to `*.js`. Then, the file gets properly loaded.

**Expected behavior**
Nuxt to autoload store modules in `*.ts` files.

**Additional context**
I gave #219 suggestions a go with no success.

Happy to provide additional context if needed :)

Thank you! 🤗

**Comment by kevinmarrec** [comment]
@afontcu Do you mind telling which steps you checked during `create-nuxt-app` configuration ? Did you enable runtime TS (it shouldn't be required but I still need to know if you enabled it or not)

**Comment by afontcu** [comment]
Hm, is it possible that it is somehow related to folder structure? I just created a new project and the .ts files appear to work correctly. In my custom project I moved all Nuxt folders to `src/`, and that's when things stop working 🤔 

---

(btw, no, didn't enable runtime TS!)

![image](https://user-images.githubusercontent.com/9197791/77409748-13196f00-6dba-11ea-8f25-4fa323fb4cfd.png)

**Comment by kevinmarrec** [comment]
@afontcu Yep, if you move files to `src` you need to tweak `srcDir` in Nuxt configuration so Nuxt correctly finds the files

**Comment by kevinmarrec** [comment]
If you share your minimal project where things aren't working anymore I'll take a look :)

**Comment by afontcu** [comment]
Okay, so this is def related to folder structure 😅 This is the desired output, which I'm unable to figure out:

```bash
/
├── src/
│   └── other-stuff/
│   └── ui/
│       ├── nuxt.config.js
│       ├── store/
│       ├── pages/
│       ├── ...
├── tsconfig.js
├── jsconfig.js
├── package.json
```

Haven't found a way to make it work with tsconfig, nuxt.config, and `@` alias 😅 Installed `@nuxt/typescript-runtime`, just in case.

The minute I set a custom `srcDir` in `nuxt.config.ts` and the `--tsconfig` flag when running nuxt-ts, then Nuxt is unable to find `tsconfig.json` 😞 I'll try to create a minimal repo

**Comment by afontcu** [comment]
Okay, getting closer 😂 

```js
```

**Comment by afontcu** [comment]
Okay, got it working by leveraging internal nuxt alias config (`@@` === `rootDir`). Anyway, closing this since this is clearly not a bug related to nuxt-typescript.

Thanks for your help though! :)

**Comment by tylermmorton** [comment]
I ran into a similar issue of the Vuex store not being activated in `*.ts` files recently. It was because I forgot to start Nuxt using `nuxt-ts` from `@nuxt/typescript-runtime` - simple mistake, hope this helps someone in the future.

```
npm install @nuxt/typescript-runtime --save-dev
```
```
// package.json
{
  "scripts": {
    "dev": "nuxt-ts"
  }
}
```
