### ISSUE TITLE
Ability to pass arguments to ts-node register when using nuxt-ts runtime

### ISSUE THREAD

**Issue by chanlito** [nuxt/typescript#329]
I'd like to be able to pass --transpile-only flag or any other flags to ts-node `register` function.
Since TS errors can be seen during dev console or editor.

**Comment by kevinmarrec** [comment]
@chanlito Is just adding a CLI (**nuxt-ts**) flag for transpilation only would be fair enough ?

**Comment by kevinmarrec** [comment]
But if you transpile only you won't have typecheck for nuxt.config.ts, serverMiddlewares and custom modules.

**Comment by chanlito** [comment]
> @chanlito Is just adding a CLI (**nuxt-ts**) flag for transpilation only would be fair enough ?

That'll work for me.

**Comment by chanlito** [comment]
> But if you transpile only you won't have typecheck for nuxt.config.ts, serverMiddlewares and custom modules.

I'm not sure about how others do their type checking, but I like to keep the webpack build running and let fork-ts-typecheck & editor do the type checking.

**Comment by kevinmarrec** [comment]
@chanlito `fork-ts-typecheck` is a Webpack plugin and only handles files that pass through Webpack, which
**Includes**:
  - Pages
  - Components
  - Plugins
  - Any file imported in the latter three
**Excludes**:
  - nuxt.config.ts
  - serverMiddlewares
  - modules

**Comment by chanlito** [comment]
Ok, but It'd be nice to be able to make execute ts-node with **transpileOnly**.

**Comment by kevinmarrec** [comment]
Will implement it though ;)

**Comment by kevinmarrec** [comment]
@chanlito I'm working on it and sounds like you were right, in fact the `fork-ts-checker` will look for everything including runtime files cause it runs the process with `tsconfig.json` which by default handle every TypeScript file under the rootDir folder

**Comment by kevinmarrec** [comment]
So I guess `nuxt-ts` can go `transpileOnly` by default
