### ISSUE TITLE
Build failing due to breaking change in @types/webpack-hot-middleware@2.25.1

### ISSUE THREAD

**Issue by johanbaaij** [nuxt/typescript#334]
**Describe the bug**
This import can not be found
https://github.com/nuxt/typescript/blob/master/packages/types/config/build.d.ts#L26

**To Reproduce**
Restart this [codesandbox](https://codesandbox.io/s/github/nuxt/typescript/tree/master/examples/options-api/minimal)

**Additional context**
There is a [PR](https://github.com/nuxt/typescript/pull/333) for this but I'm not sure it solves the problem.

My workaround was adding `@types/webpack-hot-middleware@2.25.0` to the devDependencies. Also had to delete `node_modules` and run `yarn install` again.

This is the relevant commit:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43625/commits/9d3086c9183b701c71c13759be33904123c66d99

**Comment by chanlito** [comment]
Yep, seeing this as well.

**Comment by kevinmarrec** [comment]
It's kind of boring seeing breaking type changes in a patch update 😪, I'm gonna review https://github.com/nuxt/typescript/pull/333 and release a fix ASAP !

**Comment by kevinmarrec** [comment]
https://github.com/nuxt/typescript/releases

![image](https://user-images.githubusercontent.com/25272043/79042095-210e2300-7bf5-11ea-8186-b21c01700426.png)
