### ISSUE TITLE
nuxt typeCheck: true doesn't throw type error

### ISSUE THREAD

**Issue by MYD07Shonet** [nuxt/typescript#344]
Hi i previously asked a question about type checking on following issue
https://github.com/nuxt/typescript/issues/283.

Since then i have been using ts-loader as my loader and type checking has been great. But i noticed as the project grow, the compile time when developing has grow exponentially. So i tried switching to using ForkTsCheckerWebpackPlugin following an example from the issue i mention above. Using typeCheck: true does nothing to type check.

How can i get ts-loader behaviour using ForkTsCheckerWebpackPlugin so i can improve my compile time during development without losing type check capability ?

**Comment by kevinmarrec** [comment]
@MYD07Shonet It's already this behavior by default.

Nuxt TypeScript uses `ts-loader` for transpilation only (https://github.com/nuxt/typescript/blob/master/packages/typescript-build/src/index.ts#L66), and let ForkTsCheckerWebpackPlugin (https://github.com/nuxt/typescript/blob/master/packages/typescript-build/src/index.ts#L75) checking types in external process.

**Comment by kevinmarrec** [comment]
You can't have error on browser with ForkTsCheckerWebpackPlugin, cause it's external process with errors showing up in console, but it's far faster.

**Comment by MYD07Shonet** [comment]
But the error doesn't even show up on console @kevinmarrec

**Comment by kevinmarrec** [comment]
Do you have repository with reproduction ?

**Comment by MYD07Shonet** [comment]
Sure, i will make one on this weekend. Please don't close the ticket yet :)

**Comment by kevinmarrec** [comment]
@MYD07Shonet Any updates ?
