### ISSUE TITLE
Question: More efficient way to run type checking on CI other than nuxt-ts build?

### ISSUE THREAD

**Issue by jardakotesovec** [nuxt/typescript#346]
Hi,
we would like to run type checking along with our other frontend tests on CI. `nuxt-ts build` obviously doing ton more than type checking so it takes long time. So was wondering if its feasible to somehow run only type checking?

Thank you!

**Comment by kevinmarrec** [comment]
@jardakotesovec I think you would need a standalone script that use webpack with ForkTsCheckerWebpakPlugin to achieve that :)
