### ISSUE TITLE
Support typed css-modules with typescript

### ISSUE THREAD

**Issue by sobolevn** [nuxt/typescript#35]
### What problem does this feature solve?

Currently I have to do several things to support `css-modules` in my code:

1. Create new type declaration:

```typescript
// client/shims/styles.d.ts

import Vue from 'vue'

declare module 'vue/types/vue' {
  interface Vue {
    // Augmentation to allow css-modules in .vue files:
    $style: { [key: string]: string };
  }
}
```

Source: https://github.com/wemake-services/wemake-vue-template/blob/master/template/client/shims/style.d.ts

2. Extend `webpack` configuration to work with [`typings-for-css-modules-loader`](https://github.com/Jimdo/typings-for-css-modules-loader) or [`css-modules-typescript-loader`](https://github.com/seek-oss/css-modules-typescript-loader)

And I think that it can be supported out-of-the box. It might fill in the gap between `typescript` and `css`.
My motivation is quite simple: I do not want to have runtime problems with code like this:

```vue
<template>
  <div :class="$style.actions">
    <button
      :class="$style.reload"
      @click="fetchComments"
    >
      reload comments
    </button>
  </div>
</template>

<style module>
.actions {
  text-align: center;
}

.reload {
  display: inline-block;
}
</style>
```

Full source: https://github.com/wemake-services/wemake-vue-template/blob/master/template/client/components/ActionBar.vue

Is `$style.actions` in scope? What will happen when I rename `.reload` or `.actions` classes? What if I have a typo there?
I use `typescript` to get rid of these kind of errors in my app. But now it works only with my logic (aka scripts). I also want my styles to be safe.

Maybe a plugin will also work fine. Will be happy to write it if core support is not planned. 
Next analog: https://github.com/forthedamn/next-typed-css

Cheers!

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8963">#c8963</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@sobolevn After reconsidering this feature request, I think it should be done in an external module that :
1) Extend webpack
2) Provide typings (user will need to add the module key in `types` array of `tsconfig.json`)

@pi0 Could you give me your quick point of view about this please ?

**Comment by pi0** [comment]
@kevinmarrec I like your idea. Probably we can automate some operation over `tsconfig.json` as well. Adding some option to make it manual

**Comment by kevinmarrec** [comment]
@pi0 You mean something like that ? :
Resolving module path and look for `typings` or `types` in `package.json`, if truthy, add the module name (ex: `@nuxtjs/vuetify`) to `tsconfig.json` types array ?

Shouldn't it better being the automation thing optional i.e. not activated by default and being activated through a `@nuxt/typescript-build` option ?
Not a big fan of overriding user files without his consent by default.

**Comment by sobolevn** [comment]
Is there any new issue / repo to track the module progress?

**Comment by kevinmarrec** [comment]
@sobolevn No but I'd recommend that you or someone else create its own repository and can publish a package with a name like `nuxt-whatever-you-want`, like our core team @manniL did for https://github.com/Developmint/nuxt-webfontloader.
