### ISSUE TITLE
Cannot get chokidar dependencies correctly

### ISSUE THREAD

**Issue by charlie0228** [nuxt/typescript#359]
**Describe the bug**
After removing the type of `chokidar` in `@nuxt/types` may accidentally get errors with incorrect lock files.
Related to #77 

**Expected behavior**
Correct type check when `npm run dev`

**Screenshots**
![image](https://user-images.githubusercontent.com/24387287/82238374-c2616500-9969-11ea-8b2c-450e8b8c68b1.png)

**Additional context**
Maybe can easily fix by adding `chokidar` as `devDependencies` to `@nuxt/types`

**Comment by kevinmarrec** [comment]
@charlie0228 Please provide a reproduction repository

**Comment by kevinmarrec** [comment]
`chokidar` is shipped by `nuxt` FYI

**Comment by charlie0228** [comment]
@kevinmarrec here is the reproduction repository
https://github.com/charlie0228/chokidar-error

**Comment by kevinmarrec** [comment]
@charlie0228 Sounds to be an issue with `npm`, `chokidar` should be installed in `node_modules`.

No issues with `yarn` so far, also could you make a **minimal** repository ? There are too many additional dependencies in your project that could interfer as well.

**Comment by charlie0228** [comment]
@kevinmarrec I already updated the minimal repository, thanks
https://github.com/charlie0228/chokidar-error

**Comment by kevinmarrec** [comment]
@charlie0228 This is not reproducible with last versions of following packages :
`@nuxt/types`
`@nuxt/typescript-build`
`@nuxt/typescript-runtime`

If you fall into some issues regarding `core-js`, add the following to your `package.json` :
```js
"resolutions": {
  "core-js": "2"
}
```

And finally, if you still have issues, it's more likely `npm` doing wrong things, I personally use `yarn`.
