### ISSUE TITLE
For now i added the following to my `tsconfig.json`:

### ISSUE THREAD

**Issue by houxinyu-neu** [nuxt/typescript#364]
For now i added the following to my `tsconfig.json`:
```json
"compilerOptions": {
    "skipLibCheck": true
}
```

_Originally posted by @P-de-Jong in https://github.com/nuxt/typescript/issues/49#issuecomment-471277645_
Why it works？

**Comment by kevinmarrec** [comment]
https://www.typescriptlang.org/docs/handbook/compiler-options.html

> **`skipLibCheck`** Skip type checking of all declaration files (*.d.ts).

It ignores any issue that you can have in your declartion files, so, yes, it ignores any type conflict between libraries (#49 case)
