### ISSUE TITLE
vue-router 3.3.3 breaks nuxt/types: Property component does not exist on RouterConfig

### ISSUE THREAD

**Issue by j1gs4w** [nuxt/typescript#374]
https://github.com/vuejs/vue-router/pull/3218/files
they changed the export of RouterConfig in a patch version (3.3.2 -> 3.3.3) which breaks nuxt/types due to the reason that components is selected from RouteConfig.

**To Reproduce**
Install vue-router 3.3.3 and try to compile a nuxt with typescript.
"Property component does not exist on RouterConfig"

**Expected behavior**
Do not break.

**Screenshots**
![image](https://user-images.githubusercontent.com/10881796/84492868-23e5cc80-aca7-11ea-8eb5-d66de042a723.png)

**Possible fix**
either try to get SingleRouterConfig exported and select this one, or define component by our own:
```
import Vue, { ComponentOptions, PluginFunction, AsyncComponent } from 'vue'	import Vue, { ComponentOptions, PluginFunction, AsyncComponent } from 'vue'
type Component = ComponentOptions<Vue> | typeof Vue | AsyncComponent
```

**Comment by xavism** [comment]
same here, thx @kevinmarrec for taking care! 👍

**Comment by kevinmarrec** [comment]
Something coming up in the next minutes :)
