### ISSUE TITLE
Upgrade fork-ts-checker-webpack-plugin (typescript-build package) to version 5

### ISSUE THREAD

**Issue by vasisouv** [nuxt/typescript#379]
**Is your feature request related to a problem? Please describe.**
The currently used version of [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) ([4.1.6](https://github.com/nuxt/typescript/blob/master/packages/typescript-build/package.json#L20)) has several issues some of which are listed in [this](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/404) thread. Also, some high memory usage issues are probably caused by the previous version of the plugin as noted [here](https://github.com/nuxt/typescript/issues/355#issuecomment-628720556).

**Describe the solution you'd like**
The plugin was recently updated to v5 (https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/445). It would be nice to use the latest version in nuxt/ts

**Comment by kevinmarrec** [comment]
@vasisouv  I'm trying to update it but I'm not able to type check `.vue` files with their new version, even with `typescript.extensions.vue` option :/
