### ISSUE TITLE
asyncData doesn't add the return variables to CombinedVueInstance (this)

### ISSUE THREAD

**Issue by xavism** [nuxt/typescript#380]
**Describe the bug**
When an object is returned by asyncData, it is not added to CombinedVueInstance (like data() does). An error is thrown when ts type checking

```typescript
import Vue from 'vue'
import { PoliticalMarket } from '@/entities/political.market.model'
export default Vue.extend({
  asyncData({ params }): { id: string } {
    return {
      id: params.id
    }
  },
  mounted() {
    console.log(this.id)
  }
})
````

```bash
ERROR: Property 'id' does not exist on type 'CombinedVueInstance<Vue, ... , Readonly<Record<never, any>>>'.
```

**Expected behavior**
Should add the property to CombinedVueInstance, like data() does

**Screenshots**
![Screenshot 2020-06-17 at 12 14 26](https://user-images.githubusercontent.com/11585058/84886539-dd241800-b094-11ea-9ad4-c22a27659192.png)

![Screenshot 2020-06-17 at 12 14 47](https://user-images.githubusercontent.com/11585058/84886551-e0b79f00-b094-11ea-8045-31dd608249b0.png)

**Comment by rchl** [comment]
You'd need to duplicate those properties in `data` object.

**Comment by kevinmarrec** [comment]
@xavism Sorry, there is no support for this, Nuxt `asyncData` can't extend `CombinedVueInstance` which is a `Vue` complex type.

As @rchl just stated, you need to set defaults and declare your types in `data` :

```
export Vue.extend({
  data() {
    return {
      id: null as String | null,
      someArrayOfStrings: [] as String[]
    }
  }
})
```

**Comment by xavism** [comment]
Perfect then! thank you both @rchl @kevinmarrec

**Comment by thisismydesign** [comment]
After using the proposed workaround I get warnings like this:
> [Vue warn]: Property or method "xyz" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://v2.vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

This is actually what I did in the workaround, initialized the property in `data`.
