### ISSUE TITLE
this.$config isn't typed

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#386]
```
"@nuxt/typescript-build": "^1.0.3",
"@nuxt/typescript-runtime": "^0.4.10",
"nuxt": "^2.13.1",
```

Cannot use `this.$config` in a component:

```
mounted() {
  console.log('current env', this.$config)
}
```

gives an error about untyped `this.$config`

**Comment by WTDuck** [comment]
Related issue : https://github.com/nuxt/nuxt.js/issues/7596

**Comment by kevinmarrec** [comment]
@webcoderkz You need to upgrade to latest `@nuxt/types` which is now equal to `nuxt` version.

Lot of updates (including documetation) are coming soon !

**Comment by webcoderkz** [comment]
@kevinmarrec but `@nuxt/typescript-build` has `@nuxt/types` already. How can i update `@nuxt/typescript-build` dependency myself? Isn't its up to you?

**Comment by kevinmarrec** [comment]
@webcoderkz Next major version of `@nuxt/typescript-build` will have the breaking change of not shipping `@nuxt/types` anymore, users will need to install it on their own to match their `nuxt` version, so the types are the same version of the framework.

```
yarn add @nuxt/types
```
is enough to install last version in your project and fix your `$config` types ;)

**Comment by webcoderkz** [comment]
Ah, i see now, thanks!
