### ISSUE TITLE
fork-ts-checker-webpack-plugin (typescript-build package) require versions is incorrect 

### ISSUE THREAD

**Issue by hanh-dev** [nuxt/typescript#389]
I use lerna to install nuxtjs and nestjs for my project, so my fork-ts-checker-webpack-plugin having two versions 5.x and 4.1.6, this.nuxt.resolver.resolveModule code below require fork-ts-checker-webpack-plugin 5.x version instead of version 4.1.6
![image](https://user-images.githubusercontent.com/20147479/86197471-a283aa80-bb7f-11ea-9384-fcfd2be7c8ee.png)

My current solution is install it on package.json in nuxt app
![image](https://user-images.githubusercontent.com/20147479/86202593-daddb580-bb8c-11ea-890c-93420fe5088a.png)

Can remove it in the next versions?

**Comment by kevinmarrec** [comment]
@hanh-dev We can't remove it, it's a main feature 😅, but I'm currently trying to upgrade it to **5.x** so it will fix your issue :)

**Comment by kevinmarrec** [comment]
(If it installs **5.x** it means another package you're using is requiring **5.x** somehow)

**Comment by hanh-dev** [comment]
this.nuxt.resolver.resolveModule returned 5.x, when i remove it, it worked again.
![image](https://user-images.githubusercontent.com/20147479/86211303-5f85ff00-bba0-11ea-9d57-1abec4859d76.png)

I think the reason is fork-ts-checker-webpack-plugin installed in typescript-build
![image](https://user-images.githubusercontent.com/20147479/86211437-9d832300-bba0-11ea-9a6e-5e133fc7d717.png)

but this.nuxt.resolver.resolveModule inside @nuxtjs/core requiring fork-ts-checker-webpack-plugin 5.x on root node_modules of nestjs
![image](https://user-images.githubusercontent.com/20147479/86211831-2a2de100-bba1-11ea-89d9-36d849eb32de.png)

See here
https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md#example

**Comment by kevinmarrec** [comment]
See https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/452 why I can't upgrade to **5.x** for now, I suggest you to do this instead in your `package.son` :

```js
"dependencies": {
  // ...
},
"resolutions": {
  "fork-ts-checker-webpack-plugin": "4.1.6"
}
```
To force **nextjs** to use **4.1.6** and fix your issues.

**Comment by hanh-dev** [comment]
I installed it inside package.json of nuxt app
![image](https://user-images.githubusercontent.com/20147479/86214076-dfae6380-bba4-11ea-8070-d5456efabe76.png)

force 5x version inside node_modules of @nextjs, I still hope to fix it inside typescript-build package
![image](https://user-images.githubusercontent.com/20147479/86213987-bf7ea480-bba4-11ea-81a8-24adb92bd123.png)

**Comment by kevinmarrec** [comment]
@hanh-dev It will be fixed when the package will be fixed 😅, the new version doesn't provide errors for `*.vue` files anymore, and it's the main feature 😅
