### ISSUE TITLE
Can't access data from methods, can't type `this` accurately 

### ISSUE THREAD

**Issue by quirkles** [nuxt/typescript#390]
**Describe the bug**
I'm getting all sorts of unexpected type issues despite following the docs and I can't get to the bottom of them. I can't access my data fields, the dollar sign attributes can't be found

<img width="969" alt="Screen_Shot_2020-07-01_at_12 58 11_PM" src="https://user-images.githubusercontent.com/5017593/86280277-7c730000-bba9-11ea-9e90-6c14e4e1e3c7.png">
<img width="1057" alt="Screen_Shot_2020-07-01_at_1 10 55_PM" src="https://user-images.githubusercontent.com/5017593/86280281-7c730000-bba9-11ea-9047-c89a96fc9898.png">

**To Reproduce**
My repo is here https://github.com/quirkles/wardrobe-client-new and the file shown above is 
https://github.com/quirkles/wardrobe-client-new/blob/master/pages/signup.vue

I've followed the guides accurately, to my knowledge, I can't figure out why I'm having this issue.

**Comment by kevinmarrec** [comment]
@quirkles You need to use `Vue.extend`

```ts
import Vue from 'vue'

export default Vue.extend({
  data () {
    // ...
  }
})
```

**Comment by quirkles** [comment]
D'oh really? It's that simple? Thanks I'll try when I get back. I feel like an idiot lol.

**Comment by kevinmarrec** [comment]
It's in the documentation https://typescript.nuxtjs.org/cookbook/components/, but don't feel like an idiot ;)

**Comment by quirkles** [comment]
Haha I honestly don't know how I missed that, what threw me was it was all basically working if I explicitly typed `this`in the parentheses so I assumed it couldn't be anything that fundamental. Thanks again!

**Comment by kevinmarrec** [comment]
@quirkles No problem !
