### ISSUE TITLE
dev server: Inform user about scope of memory limit

### ISSUE THREAD

**Issue by kootoopas** [nuxt/typescript#392]
Hello. :wave: 

Currently the scope of the memory limit is not expressed precisely through the dev server message:
![image](https://user-images.githubusercontent.com/601001/86468217-9fcfb380-bd3f-11ea-8467-b14659f16a80.png)

I'm assuming that the memory limit is being applied to **each** worker, therefore the message for this case should have been:
```
  Using 2 workers with 3072mb memory limit for each one
```

**Comment by kevinmarrec** [comment]
@kootoopas Hi, this is not an ouput of our module, but of https://github.com/TypeStrong/fork-ts-checker-webpack-plugin we're using under the hood. I've been upgrading the module to their last package version and there will be soon a release, but overall the message is up to them and not us :)

Closing as there's nothing to do around this module.

You can check their package if the message has been changed with **v5** until I release the new version :)

**Comment by kootoopas** [comment]
@kevinmarrec  Oh, I see, will be forwarding the message to them! Thanks for the prompt reply.
