### ISSUE TITLE
components: No overload matches this call

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/typescript#398]
After upgrading to `@nuxt/typescript-build` `2.0.0` and adding `@nuxt/types` `2.13.3` to my `package.json`, I get the following error when running `nuxt-ts generate` that references the `@Component` decorator:

```
TS2769: No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>> & ThisType<...>): <VC extends VueClass<...>>(target: VC) => VC', gave the following error.
    Type 'typeof import("*.vue")' is not assignable to type 'VueConstructor<Vue> | FunctionalComponentOptions<any, PropsDefinition<any>> | ComponentOptions<never, any, any, any, any, Record<...>> | AsyncComponentPromise<...> | AsyncComponentFactory<...>'.
      Type 'typeof import("*.vue")' is not assignable to type 'AsyncComponentFactory<any, any, any, any>'.
        Type 'typeof import("*.vue")' provides no match for the signature '(): { component: AsyncComponentPromise<any, any, any, any>; loading?: VueConstructor<Vue> | FunctionalComponentOptions<Record<string, any>, PropsDefinition<Record<string, any>>> | ComponentOptions<...> | EsModuleComponent | undefined; error?: VueConstructor<...> | ... 3 more ... | undefined; delay?: number | undefined; timeout?: number | undefined; }'.
  Overload 2 of 2, '(target: VueClass<Vue>): VueClass<Vue>', gave the following error.
    Argument of type '{ components: { Button: typeof Button; }; }' is not assignable to parameter of type 'VueClass<Vue>'.
      Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did you mean to write 'component'?
```

This is the template I use:

```vue
<template>
...
</template>

<script lang="ts">
import { Component, Vue } from 'nuxt-property-decorator'

import Button from '~/components/Button.vue'

@Component({
  components: {
    Button,
  },
})
export default class extends Vue {
  ...
}
</script>
```

What am I doing wrong?

**Comment by kevinmarrec** [comment]
@dargmuesli Is there a way you can share a repository with the described issue ? Thanks :)

**Comment by dargmuesli** [comment]
Sure! https://github.com/dargmuesli/components-issue/

**Comment by kevinmarrec** [comment]
@dargmuesli Thanks, gonna take a look

**Comment by kevinmarrec** [comment]
@dargmuesli I don't see the error you mentioned in this repository.

Also :

1) Nuxt TypeScript packages are not up to date
2) `vue-shim.d.ts` is wrong, it should be only what states the documentation : https://typescript.nuxtjs.org/guide/setup.html#configuration
3) Make your `Button.vue` functional at least to not have `render function or template not defined in component` error

**Comment by dargmuesli** [comment]
Oh sorry, I forked from the wrong commit, but the issue still showed to me somehow (caching?).
I've updated the repo, but I'm not sure if `3.` still applies.

**Comment by kevinmarrec** [comment]
@dargmuesli 

1) Fix your `vue-shim.d.ts` again, it's `export default Vue`, not `export default { Vue }`
2) Add `template` section to `events/index.vue` to make it valid component

3) Notice your project works :)

**Comment by dargmuesli** [comment]
Oh my, thanks! Sorry for the hassle. I don't understand what `vue-shim.d.ts` does as I'm quite new to that. Do you have a quick link to a good learning resource for me?
And why did this start to be a problem with the new release? :0

It seems to be enough to have (unused) import statements in that file and only use the `Vue` import for the `export default`.
