### ISSUE TITLE
this.$store dont see

### ISSUE THREAD

**Issue by mkalayci35** [nuxt/typescript#400]
"@nuxt/typescript-build": "^2.0.0",
"@nuxt/typescript-runtime": "^1.0.0",

**Screenshots**
<img width="611" alt="Screen Shot 2020-07-07 at 07 35 12" src="https://user-images.githubusercontent.com/38668796/86711197-655a6500-c024-11ea-9fef-d5f628e6e220.png">

**Comment by kevinmarrec** [comment]
@mkalayci35 You're probably missing `@nuxt/types` under `compilerOptions.types` array in `tsconfig.json` :)

**Comment by mkalayci35** [comment]
yarn add -D @nuxt/types problem fix
