### ISSUE TITLE
How to type context and inject inside a plugin?

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#405]
```typescript
import { Context } from '@nuxt/types'
import createSupportRepo from '@/api/support.repo'

export default (ctx: Context, inject: any) => {
  const repositoryWithAxios = createSupportRepo(ctx.$axios)
  inject('supportRepo', repositoryWithAxios)
}
```

How can i type `inject` there?

**Comment by kevinmarrec** [comment]
It's all here : https://typescript.nuxtjs.org/cookbook/plugins.html

**Comment by webcoderkz** [comment]
@kevinmarrec i saw this, but isn't `inject()` is a built-in function?

**Comment by kevinmarrec** [comment]
@webcoderkz What do you mean by `built-in` ? 

Its type is defined here : https://github.com/nuxt/nuxt.js/blob/dev/packages/types/app/index.d.ts#L53

You need to use `Plugin` to type your function and have proper type of `inject` which is just `(key: string, value: any) => void` cause you can inject anything.

I'm really not sure what more you're looking for

**Comment by kevinmarrec** [comment]
Using `Plugin` it automatically type the function params `ctx` & `inject`

**Comment by webcoderkz** [comment]
Ah, i see, `Plugin` is what i needed, thanks.
