### ISSUE TITLE
module resolution has problem

### ISSUE THREAD

**Issue by Yama-Tomo** [nuxt/typescript#415]
**Describe the bug**
There are a few problems.

- Not working if not exists `ts-loader` in root node_modules.
- Not working if it doesn't match the expected version of `fork-ts-checker-webpack-plugin` in root node_modules.

The installation path of package is varies by dependencies of projects, the use of yarn(or npm).
We need a module resolution that is not affected by this.

**To Reproduce**
#### ts-loader
- clone the forked repo: https://github.com/Yama-Tomo/typescript
  - don't run yarn install in the repository root
- checkout `reproduction-ts-loader-error` branch
- run cd examples/options-api/minimal/ && yarn && yarn dev

#### fork-ts-checker-webpack-plugin
- clone the forked repo: https://github.com/Yama-Tomo/typescript
  - don't run yarn install in the repository root
- checkout `reproduction-fork-ts-checker-error` branch
- run cd examples/options-api/minimal/ && yarn && yarn dev

**Comment by kevinmarrec** [comment]
@Yama-Tomo 

First `fork-ts-checker-webpack-plugin` v5 is not compatible with `@nuxt/typescript-build` v1 cause they implemented breaking changes, that's why I needed to tweak code and release v2 of `@nuxt/typescript-build`.

For `ts-loader` and more generally when you maually setup `typescript` version, It's cause you have multiple `typescript` versions installed that things are going wrong internally around `ts-loader`.

Everything is good with `@nuxt/typescript-build@2.0` & latest TypeScript version (3.9+) so I won't dive into more debugging :)

**Comment by Yama-Tomo** [comment]
@kevinmarrec 

>First fork-ts-checker-webpack-plugin v5 is not compatible with @nuxt/typescript-build v1 cause they implemented breaking changes, that's why I needed to tweak code and release v2 of @nuxt/typescript-build.

This is just one example.

my point is
- `@nuxt/typescript-build`  is dependent on the installation path of `ts-loader` and `fork-ts-checker-webpack-plugin`.
  - We expect these packages to be installed directly under node_modules.
- Depending on the project's dependencies, multiple versions of the package may be installed.
- The installation path of a package depends on the dependencies of project. It is not necessarily installed directly under node_modules.

**Comment by kevinmarrec** [comment]
> We expect these packages to be installed directly under node_modules
Well I don't know how it is supposed to be elsewhere, globally Node speaking, packages are always installed in `node_modules` 

> Depending on the project's dependencies, multiple versions of the package may be installed
When a project meets this point, it's developer job to use selective `resolutions` (https://classic.yarnpkg.com/en/docs/selective-version-resolutions) to avoid issues.

> The installation path of a package depends on the dependencies of project. It is not necessarily installed directly under node_modules.
See my first point, I don't get where it is supposed to be then
