### ISSUE TITLE
Error when importing components without .vue extension in TypeScript

### ISSUE THREAD

**Issue by cretueusebiu** [nuxt/typescript#42]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/zrl1qrlo3p](https://codesandbox.io/s/zrl1qrlo3p)

### Steps to reproduce

Go to the CodeSandbox reproduction link and open the terminal window.

### What is expected ?

Resolve .vue files without throwing errors in the terminal.

### What is actually happening?

It resolves .vue files but still throws an error in the terminal.

```
ERROR  in ~/pages/index.vue 
Cannot find module '~/components/HelloWorld'.

import HelloWorld from "~/components/HelloWorld";
``` 

![screenshot_1](https://user-images.githubusercontent.com/1517945/53090684-d6c17280-3518-11e9-9937-081994c5d36a.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8696">#c8696</a>)</em></sub></div>

**Comment by rafasegat** [comment]
How do I fix it?

**Comment by rafasegat** [comment]
It says: 
`  26:31  error  Missing file extension for "~/components/employee/layout/Sidebar"        import/extensions
  26:31  error  Unable to resolve path to module '~/components/employee/layout/Sidebar'  import/no-unresolved
  27:30  error  Missing file extension for "~/components/employee/layout/Header"         import/extensions
  27:30  error  Unable to resolve path to module '~/components/employee/layout/Header'   import/no-unresolved
  28:30  error  Missing file extension for "~/components/employee/layout/Footer"         import/extensions
  28:30  error  Unable to resolve path to module '~/components/employee/layout/Footer'   import/no-unresolved`

**Comment by rafasegat** [comment]
Here is the solution: [https://github.com/nuxt/nuxt.js/issues/200](200)
