### ISSUE TITLE
typescript is not supported while use command 'nuxt <dir>'

### ISSUE THREAD

**Issue by SakuraWood** [nuxt/typescript#422]
**Describe the bug**
use **yarn nuxt dev** is no problem. 

use **yarn nuxt dev dir ** found that typescript is not supported.

**Screenshots**

![Lark20200731153934](https://user-images.githubusercontent.com/19546612/89012084-2201c680-d344-11ea-8816-e2e39363c9b1.png)
![Lark20200731153958](https://user-images.githubusercontent.com/19546612/89012089-2332f380-d344-11ea-8697-380af887e6fe.png)

**Comment by kevinmarrec** [comment]
@SakuraWood If you're using TypeScript in runtime files you need `@nuxt/typescript-runtime` and use `nuxt-ts`.
Seen in the following documentation : https://typescript.nuxtjs.org/guide/runtime.html

It seems you're using an `interface` somewhere it is not supported, it can also be mistake in configuration of `@nuxt/typescript-build`.

If it doesn't help you, please provide a repository reproduction so I can take a look :)

**Comment by kevinmarrec** [comment]
@SakuraWood Any update ?
