### ISSUE TITLE
Linting: head() function doesn't recognize data properties accessed through 'this'

### ISSUE THREAD

**Issue by drew-chen** [nuxt/typescript#426]
**Describe the bug**
Linting: head() function doesn't recognize data properties accessed through 'this'. This is with the options api.

**To Reproduce**

https://codesandbox.io/s/ts-with-options-api-2cmek?file=/pages/index.vue:101-129

Fork the example in the docs: https://typescript.nuxtjs.org/examples/options-api/minimal.html
After that, add a head() function.

**Expected behavior**

Linter should recognize that it's from data().
Currently, I'm just ignoring certain lines.

**Comment by kevinmarrec** [comment]
@drew-chen You may need to do in some cases :

```ts
import Vue from 'vue'
import { MetaInfo } from 'vue-meta'

export default Vue.extend({
  head (): MetaInfo {
    return {
      // head stuff
    }
  }
})
```

**Comment by drew-chen** [comment]
Ah thank you. That should added that to [documentation ](https://nuxtjs.org/guide/typescript/).
