### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by jfarraraains** [nuxt/typescript#436]
I am sure you have this covered somewhere but I could not find what your plans are or where your roadmap is located.

**Comment by kevinmarrec** [comment]
@jfarraraains For now you can use https://github.com/nuxt-community/composition-api which setup Composition API while adding Nuxt related features in Composition API fashion.

https://composition-api.nuxtjs.org/

Still see :
> the main aim is to allow experimentation and feedback before the final release of Nuxt 3. It is not recommended to use this package in production.

Vue 3 support is not tied to TypeScript module itself and is planned to be shipped with Nuxt 3, in other terms Nuxt 3 will support Vue 3 and will implement similar features you can already find in the `@nuxtjs/composition-api` package.

**Comment by jfarraraains** [comment]
There is one more feature that would be awesome in Nuxt 3. The ability to build modules that can be imported into projects. Right now the whole structure is nested as a mega app. What if there were an app or module folder where the same type structure could exist inside the app or module.

/module/myModule/components
/module/myModule/layout ???
/module/myModule/middleware ???
/module/myModule/pages
/module/myModule/static
/module/myModule/store

**Comment by rchl** [comment]
This module is for Nuxt 2 and Nuxt 3 supports typescript natively so there is nothing to do here.
