### ISSUE TITLE
Compatibility issues VSCode x TypeScript x SFC

### ISSUE THREAD

**Issue by bissolli** [nuxt/typescript#438]
Hey guys,

I just started implementing TypeScript on an existing project that was done in Vue 2 as a SPA that has being recently migrated to Nuxt and I've been facing some issues around VSCode x Typescript, just want to see if anyone here has any hint to share on it since I couldn't find anything related in the internet.

**Issue 1**: 
"Go to definition" takes me to the `.d.ts` file instead of the actual `.vue` imported inside of a `.ts` file. I found many things about that on the internet, but none of them had a proper solution.

Example: 
> Button.spec.ts
```javascript
import { shallowMount } from '@vue/test-utils'
import Button from '../Button.vue' // this takes me to the `vue-shim.d.ts`

describe('Button', () => {
  test('is a Vue instance', () => {
    ...
  })
})
```

**Issue 2**: 
Is there a way to get typescript hints/auto completion inside of the `template` tag in a `.vue` file which the script tag is a `lang="ts"`?

Example:
> Button.vue
```html
<template>
  <div>
    <!-- Any chance of getting any kind of help with auto completion here? -->
    <p>{{ props.message }}</p> 
    <p v-if="props.showIcon">my icon here</p>
  </div>
</template>

<script lang="ts">
interface IButtonProps {
  message: string
  showIcon: boolean
}

export default defineComponent<IButtonProps>({
  name: 'AtomButton',
})
</script>
```

Is there a good solution in the community to get through this problems?

Sorry if this is not the best place to ask it 😅  and thanks for the support!

**Comment by kevinmarrec** [comment]
Hi @bissolli , both of your issues are not related to the Nuxt TypeScript support but directly to the VSCode Vetur extension which is reponsible of things like `Go to definition`, hints, auto completion and so on (Text editor things).

You can create an issue for the *Issue 1* or maybe find an already created issue on the same topic here :  https://github.com/vuejs/vetur/issues

For issue 2 I remember there's work going on to provide better hints in `template` section, and it seems it's stil experimental and that you can try it, see https://vuejs.github.io/vetur/interpolation.html and instructions to enable it in VSCode.

As there's finally nothing to do with the Nuxt TypeScript support itself, I'm closing the issue and wishing you all the best to find your solutions around Vetur repository & documentation :)
