### ISSUE TITLE
Support Typescript 4

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/typescript#439]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that I can't use Typescript 4 in my project. `@nuxt/typescript` explicitly pulls `typescript@~3.9`, so not only I end up with two typescripts, it also breaks nuxt project compile, see https://github.com/nuxt/typescript/issues/172#issuecomment-684884956

**Describe the solution you'd like**
I'd like the dependency to be broadened to include `typescript@~4.0`

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by kevinmarrec** [comment]
@IlyaSemenov New release with TS4 planned today :)
