### ISSUE TITLE
Can't import any component with lang='ts'

### ISSUE THREAD

**Issue by haexhub** [nuxt/typescript#445]
**Describe the bug**
I started a new nuxt project with typescript support and tried to import a SFC with typescript (lang='ts'). In every older project it was possible without any issue, but the current nuxt version seems broken.

**To Reproduce**
1. yarn create nuxt-app
2. choose Typescript
3. yarn dev
4. try to change the script tag in any SFC to <script lang='ts'>....</script>
5. error => the component can't be loaded 

**Expected behavior**
Any SFC with lang='ts' should be loaded normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/29780781/93345736-74833d80-f833-11ea-80d1-8dc1896d285d.png)

![image](https://user-images.githubusercontent.com/29780781/93345650-5d445000-f833-11ea-898a-6f10573bd930.png)

**Comment by haexhub** [comment]
can someone confirm this?

**Comment by kevinmarrec** [comment]
@haexhub What do you mean by `try to change the script tag in any SFC to <script lang='ts'>....</script>` ?

Default TypeScript project has its `index.vue` with `lang="ts"` tag and works fine.

I don't have any issue with new projects, so please provide a repository with your issue.

**Comment by haexhub** [comment]
You are right. 
Tried it again and now its working. 
Thank you for your help!
