### ISSUE TITLE
Scroll Behaviour type support in 'app/router.scrollBehavior.ts'

### ISSUE THREAD

**Issue by e-lobo** [nuxt/typescript#446]
right now doing this 

```
import { Route } from "vue-router";

const scrollBehavior = (to: Route, from: Route, savedPosition: any) => {
  console.log(savedPosition);
  console.log(to);
  console.log(from);
  return { x: 0, y: 0 };
};
export default scrollBehavior;
```

has no affect. (console.log shows nothing) whereas changing it to .js works fine.
im trying to push to a page (kept alive) with the last saved position.

**Comment by kevinmarrec** [comment]
@e-lobo Unfortunately there is no support for TypeScript for this feature, you may want to try with `nuxt-ts`, but I think it's overall tied to Nuxt internals which looks for a `.js` file.

**Comment by e-lobo** [comment]
@kevinmarrec yes i am using it with `nuxt-ts`.. works with `.js` only

**Comment by kevinmarrec** [comment]
@e-lobo Yeah so I was right, there's no currently workaround for now, I'm myself using a `.js` version in my Nuxt TypeScript projects. I will reach Nuxt Core Team to see if we can enable TypeScript support for this file for Nuxt 3.

**Comment by aletz13** [comment]
I have this in one of my projects. It is a vue-cli project so not sure if you can use it for nuxt but here you go...

```
import { RouterScrollBehavior } from 'vue-router';

const scrollBehavior: RouterScrollBehavior = (to, from, savedPosition) => {
  // Different return options here
}
```

**Comment by danielroe** [comment]
For what it's worth, `app/router.scrollBehavior.ts` works fine for me.

**Comment by gigamarr** [comment]
Extended @aletz13's version for nuxt `2.15.8`

```
import { RouterOptions } from 'vue-router'

const scrollBehavior: RouterOptions['scrollBehavior'] = (to, from, savedPosition) => {
    // ...
}

export default scrollBehavior
```

**Comment by rchl** [comment]
This is really something that would have to be addressed in Nuxt 2 itself. It would have to be extended with logic that considers *.ts files a valid overrides and make them override the original *.js files. This module can't do that.
