### ISSUE TITLE
Property 'setBaseURL' does not exist on type 'AxiosInstance'.

### ISSUE THREAD

**Issue by webcoderkz** [nuxt/typescript#447]
Example code:

```js
import { Context } from '@nuxt/types'

export default function (
  { $axios }: Context,
  inject: (key: string, value: any) => void
) {
  // Create a custom axios instance
  const api = $axios.create({
    headers: {
      common: {
        Accept: 'text/plain, */*',
      },
    },
  })
  api.setBaseURL('asdsad') // this line causes an error
  inject('cms', api)
}

```

Looks like `setBaseURL` is not typed in `@nuxt/types`

**Comment by kevinmarrec** [comment]
@webcoderkz You're missing `@nuxtjs/axios` in your `tsconfig.json` `types` array, which loads Nuxt Axios extended types (which includes `setBaseURL`)

![image](https://user-images.githubusercontent.com/25272043/94119160-cdb02a00-fe4e-11ea-9166-296d07394a8d.png)

https://github.com/nuxt-community/axios-module/blob/master/types/index.d.ts#L16

**Comment by webcoderkz** [comment]
@kevinmarrec i have it, i've used the file above as a plugin, when i create a new instance, it has no typings for methods. I've tried to do:

```js
  const api: NuxtAxiosInstance = $axios.create({
    headers: {
      common: {
        Accept: 'text/plain, */*',
      },
    },
```

Then i get an error: "TS2740: Type 'AxiosInstance' is missing the following properties from type 'NuxtAxiosInstance': $request, $get, $delete, $head, and 18 more."

I just want to create a separate nuxt axios instance with a certain baseurl value.

**Comment by kevinmarrec** [comment]
@webcoderkz Oh I see, it's cause `$axios.create` returns `AxiosInstance` and not `NuxtAxiosInstance`, this is something to be fixed around https://github.com/nuxt-community/axios-module

**Comment by webcoderkz** [comment]
@kevinmarrec as a workaround i can use `const api: any` atm?

**Comment by kevinmarrec** [comment]
@webcoderkz yes or cast `api` to `NuxtAxiosInstance` type. But be careful, I'm not sure `create` returns a proper Nuxt Axios Instance with the good properties and functions.
