### ISSUE TITLE
Object literal may only specify known properties

### ISSUE THREAD

**Issue by AleeeKoi** [nuxt/typescript#452]
Hello!
I'm getting a TS error when I try to set a custom option to a Vue component.

```
[...]
<script lang="ts">
import Vue from 'vue'
import nav from './_nav'

export default Vue.extend({
  name: 'TheSidebar',
  nav,
})
</script>
```

```
    No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; nav: { _name: string; _children: ({ _name: string; name: string; to: string; icon: string; badge: { color: string; text: string; shape?: undefined; }; _children?: undefined; route?: undefined; items?: undefined; _class?: undefined; href?: undefined; target?: undefined; } | ... 5 more ... | { ...; })[...' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'.
      Object literal may only specify known properties, and 'nav' does not exist in type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<...>>'
```

So, I have tried to define a custom module in '/types/options.d.ts' like this:

```
import Vue, { ComponentOptions } from 'vue'
import { NavInterface } from '../layouts/default/_nav'

declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    nav?: Array<NavInterface>
  }
}
```

But the error persists. Any suggestions? 
Thank you

**Comment by kevinmarrec** [comment]
@AleeeKoi

**1)** You need to not export `ComponentOptions` from `vue`

**2)** I think you're type file is not loaded by TypeScript. TypeScript look by default in :
- root of your project
- `@types` folder in your project

If you're folder is named `types` and not `@types`, you need to explicitly tell to TypeScript in `tsconfig.json` that it should look that folder : https://www.typescriptlang.org/tsconfig#typeRoots

**Comment by AleeeKoi** [comment]
Hi @kevinmarrec !
Ok, thank you for your explanation. But let me understand:

In my tsconfig.json I have this default configuration
```
"types": [
      "@types/node",
      "@nuxt/types",
    ]
```
So these paths refer to what inside node_modules, true?
Or these path needs to be created in the root directory of the project and are used to put custom TS definitions?

**Comment by kevinmarrec** [comment]
@AleeeKoi 

First, sorry for the late answer.

TypeScript doesn't load `node_modules` by default, it only load root directory type files and `@types` in your root directory.

The `types` array in `tsconfig.json` is here to define either `node_modules` packages or other local paths.

**Comment by rchl** [comment]
I think this is resolved.
You can make Typescript aware of extra types by adding its path to `types` array in `tsconfig.json`. Or one of the other options like `include` or `files`.
