### ISSUE TITLE
Property '$axios' does not exist on type

### ISSUE THREAD

**Issue by raveltan** [nuxt/typescript#457]
**Describe the bug**
Property '$axios' does not exist on type
is outputed on yarn dev, even though the vscode autocomplete recoqnise it and the axios method is running properly

**To Reproduce**
1. Create a nuxt project with typescript and axios, tsc will complain about the axios type
2. add axios type to tsconfig, the error message on vscode will disapper
3. run yarn dev, and it will state that error

**Expected behavior**
The error should not exists as the type is added to tsconfig and vscode is already able to recoqnise the type.

**Additional context**
I tried clearing the node modules, yarn.lock and .nuxt a few times, but the error presists

**Comment by kevinmarrec** [comment]
Hi @raveltan 

First, If you have differences between editor & console it's because they don't use the same TypeScript version.
You may need to first to tell VSCode to use `"vetur.useWorkspaceDependencies": true` setting to be sure both use the same version.

Then, is there a way I could take a look to your projec to help you out ?
I should only need `package.json`, `yarn.lock` & `tsconfig.json` to find the issue but if you have the issue creating a new project, could you create a github repository from that ? Thanks !

**Comment by spiritbro1** [comment]
hello @kevinmarrec  i also have same issue i dont understand how to use $axios with typescript this is my code

```
import LoginAdmin from '@/components/LoginAdmin.vue'
import { Component, Vue } from 'nuxt-property-decorator'
import  Auth  from "@nuxtjs/auth";

export default class MyStore extends Vue {


public username:string="";
  public password:string="";
  public error:string="";
  async login(){
    console.log(this.$axios)
    try {

        await this.$auth.loginWith('local', {
          data: {
          email: this.username,
          password: this.password
          },
        })
console.log(this.$auth.loggedIn)
        // this.$router.push('/')
      } catch (e) {
      console.log(e.message)
      }
  }
}

```

can you please elaborate how to use ths.$auth on class? or do you have reference i try in the internet adding "@nuxtjs/axios" in tsconfig.json but still doenst work

**Comment by spiritbro1** [comment]
@raveltan i fix the issue by added ```@Component``` decorator to class also on type declarations add NuxtAxiosInstance like this 

```
// ts-shim.d.ts
import { Auth } from '@nuxtjs/auth'
import { NuxtAxiosInstance } from '@nuxtjs/axios'
declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}

declare module '@nuxt/types' {
  interface Context {
    $auth: Auth
  }
}
declare module '@nuxt/types' {
  interface Context {
    $axios: NuxtAxiosInstance
  }
}

```

put this on **ts-shim.d.ts** in your root project

don't forget to add ```@Component``` decorator in one of your component like this:

```
import { Component, Vue } from 'nuxt-property-decorator'

@Component
export default class MyStore extends Vue {
```

hope it helps

**Comment by raveltan** [comment]
Thanks for the info guys, i had migrated the project to javascript earlier this last week as i am unable to get rid of the error, but i will definitely check your suggestions if i happen to use nuxt with typescript again next time.

**Comment by seupedro** [comment]
Im my case, I was missing to use `Vue.extend({})` or `Vue.Component` as described here https://vuejs.org/v2/guide/typescript.html#Basic-Usage  and here https://typescript.nuxtjs.org/

**Comment by fahmiegerton** [comment]
I still cannot make this works. `$axios` still missing even in nuxt `context`

**Comment by danielroe** [comment]
@martinsagat If you are experiencing an issue, please raise it against https://github.com/nuxt-community/axios-module/issues

**Comment by dgrinbergs** [comment]
I have this issue too. My project is using Nuxt 2.15.8 and I've followed the instructions [here](https://axios.nuxtjs.org/setup). Is this a lost cause at this point?

Left: `/store/products.ts`
Right: `/tsconfig.json`
<img width="790" alt="image" src="https://user-images.githubusercontent.com/44690511/153795819-362b64c0-3d93-40fc-942f-d02e47fed365.png">

**Comment by danielroe** [comment]
Your editor doesn't know that is a vuex store. You can manually use the `ActionTree` type exported by vuex or use a library that exists to help provide type safety, such as my own https://typed-vuex.roe.dev or one of the others [here](https://typescript.nuxtjs.org/cookbook/store).
