### ISSUE TITLE
const emun not work expected behavior in nuxt-ts generate

### ISSUE THREAD

**Issue by Mini-ghost** [nuxt/typescript#461]
**Describe the bug**
Typescript **const emun not work expected behavior**

**To Reproduce**
1.  create a new file and add this code block below.

```ts
const enum STORAGE_KEY {
  THEME = 'theme content'
}

// do something use enum, liek console
console.log(STORAGE_KEY.THEME)
```

2. run generate ( I use `yarn generate` )
3. the generate file code like this  code block below

```js
var STORAGE_KEY;
(function (STORAGE_KEY) {
    STORAGE_KEY["THEME"] = "theme content";
})(STORAGE_KEY || (STORAGE_KEY = {}));
// do something use enum, liek console
console.log(STORAGE_KEY.THEME);
```

**Expected behavior**
If write `const enum`, the expected behavior is:

```js
// do something use enum, liek console
console.log("theme content" /* THEME */);
```

If not write `const`, just write `enum` will generate this code

```js
var STORAGE_KEY;
(function (STORAGE_KEY) {
    STORAGE_KEY["THEME"] = "theme content";
})(STORAGE_KEY || (STORAGE_KEY = {}));
// do something use enum, liek console
console.log(STORAGE_KEY.THEME);
```
but in `nuxt-ts`, code always is:

```js
var STORAGE_KEY;
(function (STORAGE_KEY) {
    STORAGE_KEY["THEME"] = "theme content";
})(STORAGE_KEY || (STORAGE_KEY = {}));
// do something use enum, liek console
console.log(STORAGE_KEY.THEME);
```

Sorry, English is not my mother tongue, I tried my best to express it, thank you!

**Comment by kevinmarrec** [comment]
@Mini-ghost What is your TypeScript version ? It may also be an issue around `ts-loader` package.

**Comment by Mini-ghost** [comment]
@kevinmarrec

Thanks your for answering.

In this issue, the `TypeScript` version I use is 4.0.3 and the `ts-loader` version is 8.0.7. And I upgraded `@nuxt/typescript-runtime` to 2.0.1 and `@nuxt/typescript-build` to 2.0.4, but it still does not meet the expected behavior.

It may be about the isssue of `ts-loader` package but I don’t know how to solve it.

Now I replaced the `const enum` with the below code, which can have the expected behavior:

```typescript
// use 'as const' 
const STORAGE_KEY =  {
  THEME: 'theme content'
} as const
```

**Comment by kevinmarrec** [comment]
@Mini-ghost 

Maybe it only works with enum with integers values ? So you're finally using an object and not an enum instead ?
