### ISSUE TITLE
Types parsing and store actions references

### ISSUE THREAD

**Issue by regislutter** [nuxt/typescript#463]
Hello,

I've started a new project and have some issues regarding the code parsing and validation by Typescript.
I have 2 issues with Axios and nuxt-i18n. In both case, the code is running and the app works, but I can't create any test with Jest on those files. I am using Visual Studio Code and I restarted it after installing the packages.

**Store actions :**
I can point to `this.$axios` or `this.$i18n` everywhere without any issue, but when using them in an store action, I got error messages : 
`Property '$axios' does not exist on type '{ currentLocaleName(): string; getUser(_: any, userId: number): Promise<unknown>; }'.ts(2339)`
Of course I added them in `tsconfig.json`.

**i18n properties :** 
When using `$i18n`, Typescript doesn't seem to be able to see the properties of `LocaleObject`. For exemple, where trying to get a `this.$i18n.locales[0].code`, you get the error : 
`Property 'code' does not exist on type 'string | LocaleObject'.`

**To Reproduce**

1. Create a new nuxt app with NPM, Axios, Typescript and Jest
2. Install nuxt-i18n and add it in `modules` in `nuxt.config.js`
3. Add `nuxt-i18n` and `@nuxtjs/axios` in `tsconfig.json`
4. Create a `index.ts` store file like this : 

```
export const actions = {
  currentLocaleName (): string {
    if (this.$i18n && this.$i18n.locales && this.$i18n.locale) {
      const _locale = this.$i18n.locales.find(i => i.code === this.$i18n.locale)
      return _locale ? _locale.name : 'Unknown'
    }
    return 'Unknown'
  },
  getUser (_: any, userId: number) : Promise<unknown> {
    return this.$axios.$get(`/cloudapi/users/${userId}`)
  }
}
```

5. Add this method in `pages/index.vue`

```
export default Vue.extend({
  methods: {
    currentLocaleName () : string {
      if (this.$i18n && this.$i18n.locales && this.$i18n.locale) {
        const _locale = this.$i18n.locales.find(i => i.code === this.$i18n.locale)
        return _locale ? _locale.name : 'Unknown'
      }
      return 'Unknown'
    }
  }
})
```

Your IDE should prompt the errors on the variables.

**Expected behavior**
Not error prompted by Typescript and Jest not blocked.

**Screenshots**

![Capture d’écran 2020-11-20 à 09 30 58](https://user-images.githubusercontent.com/214122/99777810-1e709600-2b13-11eb-901e-1171265a9326.png)

![Capture d’écran 2020-11-20 à 09 30 10](https://user-images.githubusercontent.com/214122/99777759-1153a700-2b13-11eb-9256-a2b80b1eaa4d.png)

![Capture d’écran 2020-11-20 à 09 32 58](https://user-images.githubusercontent.com/214122/99778002-65f72200-2b13-11eb-9f52-ed48c372270c.png)

Thank you for your help.

**Comment by zetura** [comment]
It think I found a workaround here `(this as any).$axios` : https://github.com/nuxt-community/hackernews-nuxt-ts/issues/11
But it should have been fixed since.

**Comment by rchl** [comment]
There are instructions in the documentation how to annotate store properly: https://typescript.nuxtjs.org/cookbook/store/#basic-typing

As for your second example with `$i18n`, this is just standard Typescript behavior that you have to handle with type narrowing or type guards. Nothing specific to this module.
