### ISSUE TITLE
Update to TypeScript 4.1

### ISSUE THREAD

**Issue by mamins1376** [nuxt/typescript#466]
**Is your feature request related to a problem? Please describe.**
The problem is the bug caused by previous versions of typescript, with following issues describing the problem:
https://github.com/typescript-eslint/typescript-eslint/issues/2127
Which seems to be fixed in the latest typescript release:
https://github.com/microsoft/TypeScript/issues/40495

**Describe the solution you'd like**
Bump typescript to `^4.1` in packages.json.

**Describe alternatives you've considered**
Maybe it is possible to have two versions of typescript installed?

**Additional context**
I love nuxt!

**Comment by P4sca1** [comment]
I am using a synced Typescript version across multiple packages in a monorepo and would like to upgrade it to 4.1 (because Prisma 2.14 requires it).
Nuxt is currently blocking the update. Would be great if Typescript 4.1 could be supported. @kevinmarrec
