### ISSUE TITLE
nuxt.config.ts router.base and router.mode settings are not working

### ISSUE THREAD

**Issue by GKennyKwok** [nuxt/typescript#468]
**Describe the bug**
I added router.base:'./' and router.mode:'hash' in nuxt.config.ts, 
and I can’t use the npm run build command to generate the relative path file I need in TypeScript, 
but I created another file without TypeScript The project is normal.
Thanks

**To Reproduce**
1. use npx create-nuxt-app, select TypeScript
2. setting 
  router:{
    mode:'hash',
    base:'./'
  },
in nuxt.config.ts
3. npm run build

**Expected behavior**
I need to generate a project for Web APP, but the absolute path cannot be used, the entry is index.html file.

**Additional context**
`
E:\sources\vue-mooli>npm run build

> vue-mooli@1.0.0 build E:\sources\vue-mooli
> nuxt-ts build

i Production build                                                                                                                                                                                                    22:18:35  
i Bundling only for client side                                                                                                                                                                                       22:18:35  
i Target: static                                                                                                                                                                                                      22:18:35  
√ Builder initialized                                                                                                                                                                                                 22:18:35  
√ Nuxt files generated                                                                                                                                                                                                22:18:35  

√ Client
  Compiled successfully in 52.69s

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of E:\sources\vue-mooli\node_modules\bootstrap-vue\src\icons\icons.js as it exceeds the max of 500KB.                                            22:18:51  

Hash: 1b219aef5d04960ae118
Version: webpack 4.44.2
Time: 52702ms
Built at: 2020-12-16 10:19:30 ├F10: PM┤
                                          Asset      Size  Chunks                                Chunk Names
                 ../server/client.manifest.json  26.9 KiB          [emitted]
                                     3271148.js  1020 KiB       4  [emitted] [immutable]  [big]  vendors/app
                                     3bec6e6.js   462 KiB       0  [emitted] [immutable]  [big]  app
                                     8b577ac.js  36.8 KiB       2  [emitted] [immutable]         pages/index
                                     90dd464.js  2.29 KiB       3  [emitted] [immutable]         runtime
                                       LICENSES     2 KiB          [emitted]
                                     e5a5359.js   209 KiB       1  [emitted] [immutable]         commons/app
            fonts/simple-Line-Icons.596814c.ttf  34.5 KiB          [emitted]
            fonts/simple-Line-Icons.f19a7f6.eot  34.7 KiB          [emitted]
           fonts/simple-Line-Icons.ff94ad9.woff  57.9 KiB          [emitted]
 fonts/weathericons-regular-webfont.2ca3df0.ttf  82.2 KiB          [emitted]
 fonts/weathericons-regular-webfont.e7ef2b4.eot  41.2 KiB          [emitted]
fonts/weathericons-regular-webfont.f5b0d0d.woff  47.2 KiB          [emitted]
              img/simple-Line-Icons.c9c9b5e.svg   177 KiB          [emitted]
   img/weathericons-regular-webfont.b2233bc.svg   156 KiB          [emitted]
 + 1 hidden asset
Entrypoint app [big] = 90dd464.js e5a5359.js 3271148.js 3bec6e6.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  3bec6e6.js (462 KiB)
  3271148.js (1020 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1000 KiB). This can impact web performance.
Entrypoints:
  app (1.65 MiB)
      90dd464.js
      e5a5359.js
      3271148.js
      3bec6e6.js

i Generating output directory: dist/                                                                                                                                                                                  22:19:31
i Generating pages                                                                                                                                                                                                    22:19:38
√ Generated route "/"                                                                                                                                                                                                 22:19:38
√ Client-side fallback created: 200.html   
`

**Comment by GKennyKwok** [comment]
this is my nuxt.config.ts file


`
import { NuxtConfig } from '@nuxt/types';

const config:NuxtConfig = {

  // srcDir

  // ENV Config
  env:{
    NODE_ENV: process.env.NODE_ENV || 'development',
    BASE_URL: process.env.BASE_URL || 'localhost',
    BASE_POST: process.env.BASE_POST || '3000',
  },

  // Disable server-side rendering (https://go.nuxtjs.dev/ssr-mode)
  ssr: false,

  // Global page headers (https://go.nuxtjs.dev/config-head)
  head: {
    title: 'vue-mooli',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: './favicon.ico' },
      { rel: "stylesheet", href: "./assets/vendor/font-awesome/css/font-awesome.css" },
      { rel: "stylesheet", href: "./assets/vendor/animate-css/vivify.min.css" },
      { rel: "stylesheet", href: "./assets/vendor/chartist/css/chartist.css" },
      { rel: "stylesheet", href: "./assets/vendor/chartist-plugin-tooltip/chartist-plugin-tooltip.css" },
      { rel: "stylesheet", href: "./assets/vendor/c3/c3.min.css" },
      { rel: "stylesheet", href: "./assets/vendor/toastr/toastr.css" },
      { rel: "stylesheet", href: "./assets/vendor/jvectormap/jquery-jvectormap-2.0.3.css" },
    ]
  },

  // Global CSS (https://go.nuxtjs.dev/config-css)
  css: [
    '~/assets/styles/custom.scss',
    '~/assets/styles/scss/main.scss'
  ],

  router:{
    mode:'hash',
    base:'./'
  },

  // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
  plugins: [
  ],

  // Auto import components (https://go.nuxtjs.dev/config-components)
  components: true,

  // Modules for dev and build (recommended) (https://go.nuxtjs.dev/config-modules)
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
  ],

  // Modules (https://go.nuxtjs.dev/config-modules)
  modules: [
    // https://go.nuxtjs.dev/bootstrap
    'bootstrap-vue/nuxt',
    '@nuxtjs/dotenv',
    '@nuxtjs/dayjs',
  ],
  
  bootstrapVue: {
    icons: true,
    bootstrapCSS: false, // Or `css: false`
    bootstrapVueCSS: false // Or `bvCSS: false`
  },

  dayjs: {
    locales: ['zh'],
    defaultLocale: 'zh'
  },

  // Build Configuration (https://go.nuxtjs.dev/config-build)
  build: {
    analyze: false,
  },

  server: {
    port: process.env.BASE_POST, // default: 3000
  },

  // serverMiddleware: [
  //   { path: "/api", handler: "~/server/app.js" }
  // ]
};

export default config;
`

my dependencies 

`
"dependencies": {
    "@nuxt/http": "^0.6.1",
    "@nuxt/typescript-runtime": "^2.0.0",
    "@nuxtjs/dayjs": "^1.2.1",
    "@nuxtjs/dotenv": "^1.4.1",
    "bootstrap": "^4.5.2",
    "bootstrap-vue": "^2.17.3",
    "core-js": "^3.6.5",
    "koa": "^2.13.0",
    "koa-body": "^4.2.0",
    "koa-orm": "^3.2.1",
    "koa-router": "^10.0.0",
    "koa-session": "^6.1.0",
    "mysql2": "^2.2.5",
    "nuxt": "^2.14.6",
    "sequelize": "^6.3.5",
    "vuelidate": "^0.7.6"
  },
`
`
  "devDependencies": {
    "@nuxt/types": "^2.14.6",
    "@nuxt/typescript-build": "^2.0.3",
    "@vue/test-utils": "^1.1.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.5.0",
    "jest": "^26.5.0",
    "node-sass": "^5.0.0",
    "sass-loader": "^10.1.0",
    "scss-loader": "0.0.1",
    "ts-jest": "^26.4.1",
    "vue-jest": "^3.0.4"
  }
`

**Comment by GKennyKwok** [comment]
I made my project public
https://github.com/GKennyKwok/vue-mooli/tree/codesandbox

Only a max of 500 modules is allowed in a sandbox sorry


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Sébastien Chopin<mailto:notifications@github.com>
发送时间: 2020年12月16日 22:54
收件人: nuxt/typescript<mailto:typescript@noreply.github.com>
抄送: 郭老师<mailto:gyz1225@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [nuxt/typescript] nuxt.config.ts router.base and router.mode settings are not working (#468)


Can you please create a reproduction on CodeSandBox? https://template.nuxtjs.org

―

**Comment by GKennyKwok** [comment]
https://codesandbox.io/s/vue-mooli-q8ecp

**Comment by rchl** [comment]
Please create new minimal reproduction if it's still a problem. The existing codesandbox doesn't work and it's not possible to export it.
