### ISSUE TITLE
Avoid importing interface definitions in all components

### ISSUE THREAD

**Issue by sebastien-metzger** [nuxt/typescript#471]
Hello,

I am starting using Typescript in my Nuxt project and after searching the whole internet I didn't find any clue to avoid importing in each component an interface definition. For instance I have created the following interface in ./types/news.ts:
```ts
export interface News {
    title: string
    content: string
    thumbnailPath: string
    type: string
}
```
And then in each page / component I need to import this interface:
```ts
import { News } from "@/types/news"
```

Do I need to use a plugin injection or configure my tsconfig.json?

Thank you for your help!
Best Regards,

**Comment by kevinmarrec** [comment]
@sebastien-metzger You mean `News` is an interface you're using really often and you would prefer to not have to import it everywhere ?

If yes, it's possible but it comes with an `eslint` drawback.

If you define an interface in a `.d.ts` in root directory (`~`) or in a `@types` folder (`~/@types`), it will become accessible in your whole project :

```ts
// ~/@types/news.d.ts
interface News {
  title: string
  content: string
  thumbnailPath: string
  type: string
}
```

Notice you need to **not** export it. If you export it, it won't be accessible in your whole project and you will need to import it manually.

Finally, the drawback is that as you won't be importing it anymore, **ESLint** `no-undef` error will show up, cause it can't know it's a globally accessible type.

**Comment by sebastien-metzger** [comment]
Hello @kevinmarrec, thank you for your response! I have chosen to define all interfaces, enum, types in a models.ts (I still don't understand the difference between .d.ts and .ts files ?) and I import it when I needed.

Actually I try to learn TypeScript (in VueJS) by adopting the good practices. I still have a long journey :)
