### ISSUE TITLE
Installing only production dependencies results in nuxt build error

### ISSUE THREAD

**Issue by tre-dev** [nuxt/typescript#473]
I'm using Nuxt with Typescript Runtime/Build and when using `npm ci --only=prod` or `NODE_ENV=production npm ci`, no dev dependancies (like webpack or @nuxt/typescript-build) are installed.

Which results in them not being found by the build command `NODE_ENV=production nuxt-ts build --modern=server` which results in Nuxt build error like `Error: Cannot find module 'webpack'.`

It seems the only way to fix it, is to install dev deps as well or is there something I'm missing?
Below is roughly the docker file I'm using

```
FROM node:13.7
WORKDIR /mydir
ARG NODE_ENV
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
RUN npm ci && npm run build
COPY . .
ENV NODE_ENV $NODE_ENV
EXPOSE PORT
CMD ["npm", "run", "start"]
And scripts section of package.json

"scripts": {
  "build": "NODE_ENV=production nuxt-ts build --modern=server",
  "start": "NODE_ENV=production nuxt-ts start --modern=server",
},
```

**Comment by danielroe** [comment]
@tre-dev You should have your development dependencies installed when you build your app. Then, you can remove all but production dependencies to run it. To produce a docker image, therefore, it's helpful to use several intermediate steps to ensure the final image is as slim as possible.

**Comment by kevinmarrec** [comment]
Hi @tre-dev ,

@danielroe is right here.

1) You need to **build** your app, and should be installed as `devDepedency` so it's correcty removed in production as after build you won't need it anymore.
2) You need  `@nuxt/typescript-runtime` to **run** your app, which means you need it in production.
 See https://typescript.nuxtjs.org/guide/runtime tip in `Installation` section.
 This package includes the `nuxt-ts` binary which is the main entry of your app when you run it.

**Comment by tre-dev** [comment]
Thanks for the answers!

I tested it again with `npm prune` and while building works, starting it doesn't.

```
RUN npm run build

RUN npm prune

CMD ["npm", "run", "start"]
```

```
"start": "NODE_ENV=production nuxt-ts start",
```

`@nuxt/typescript-runtime` is within dependancies.

**Comment by danielroe** [comment]
@tre-dev Looks like you're importing a development dependency - webpack - into your nuxt config. You should move this into a buildModule so it doesn't need to be loaded in production.

**Comment by tre-dev** [comment]
I'm using ```
import {IgnorePlugin} from 'webpack'

config.plugins.push(new IgnorePlugin(/^\.\/locale$/, /moment$/))
```

within `build: { extend: ...}`

**Comment by danielroe** [comment]
As I said, you should move this into a build module so it doesn't need to be loaded in production.

**Comment by tre-dev** [comment]
I tried that before but didn't work, now it does. I've moved the relevant code to  `~/nuxt.build`. Thanks for the help!
