### ISSUE TITLE
Combine asyncData return type with Vue component data type.

### ISSUE THREAD

**Issue by andoshin11** [nuxt/typescript#48]
### What problem does this feature solve?

While we can access the returned type information of Vue native apis (i.e. data, computed, props, methods), the return type of asyncData function is totally lost from "this" object.

I'm not sure if it's even possible to combine these type information without changes on Vue core types, but I believe it is 'must-have' goal for us to provide safe, correct, efficient type definitions for users.

I've already spent some hours to solve this problem yet I haven't seen a daylight. Hope I can rely on your help.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8568">#c8568</a>)</em></sub></div>

**Comment by nuria-fl** [comment]
Hi, I see this is closed but I'm running into the same issue, I think. I'm using the options API, but the problem remains the same. If I have this code:

```ts
interface Test {
  foo: string
  bar: number
}

export default Vue.extend({
  asyncData(): Test {
    // this is syncronous to keep the example minimal but would be the same
    return {
      foo: 'hi',
      bar: 1
    }
  },
  methods: {
    test() {
      console.log(this.foo) // error here Property 'foo' does not exist on type…
    }
  }
})
```

I see you say this is not possible, but it's a pretty core feature of nuxt and I wonder how people overcome this in their projects. The only way I've found to overcome the issue is adapting [that last code example](https://github.com/nuxt/typescript/issues/48#issuecomment-460850136) to the options API, initialising the variables with the `data` function, which it makes it clearer that it's very cumbersome and not ideal:

```ts
interface Test {
  foo: string
  bar: number
}

export default Vue.extend({
  data(): Test {
    return {
      foo: '',
      bar: 1
    }
  },
  asyncData(): Test {
    return {
      foo: 'hi',
      bar: 1
    }
  },
  methods: {
    test() {
      console.log(this.foo)
    }
  }
})
```

Let me know if you want me to open a new issue.

**Comment by kevinmarrec** [comment]
@nuria-fl The infered types from `data` is done by Vue official types, I don't have any clue yet if we can override it to make it infer both types of `data` & `asyncData`.

**Comment by HermitSun** [comment]
> Hi, I see this is closed but I'm running into the same issue, I think. I'm using the options API, but the problem remains the same. If I have this code:
> 
> ```ts
> interface Test {
>   foo: string
>   bar: number
> }
> 
> export default Vue.extend({
>   asyncData(): Test {
>     // this is syncronous to keep the example minimal but would be the same
>     return {
>       foo: 'hi',
>       bar: 1
>     }
>   },
>   methods: {
>     test() {
>       console.log(this.foo) // error here Property 'foo' does not exist on type…
>     }
>   }
> })
> ```
> 
> I see you say this is not possible, but it's a pretty core feature of nuxt and I wonder how people overcome this in their projects. The only way I've found to overcome the issue is adapting [that last code example](https://github.com/nuxt/typescript/issues/48#issuecomment-460850136) to the options API, initialising the variables with the `data` function, which it makes it clearer that it's very cumbersome and not ideal:
> 
> ```ts
> interface Test {
>   foo: string
>   bar: number
> }
> 
> export default Vue.extend({
>   data(): Test {
>     return {
>       foo: '',
>       bar: 1
>     }
>   },
>   asyncData(): Test {
>     return {
>       foo: 'hi',
>       bar: 1
>     }
>   },
>   methods: {
>     test() {
>       console.log(this.foo)
>     }
>   }
> })
> ```
> 
> Let me know if you want me to open a new issue.

Maybe we can use type assertion to let TypeScript know our Vue instance's data type? Just like this:

```ts
interface Test {
  foo: string;
  bar: number;
}

export default Vue.extend({
  asyncData() {
    return {
      foo: 'hi'
    };
  },
  data() {
    return {
      bar: 1
    } as Test;
  },
  methods: {
    test() {
      console.log(this.foo);
    }
  }
});
```
This works for me. And I hope we can solve it in the coming Vue 3.0.

**Comment by dora-gt** [comment]
I hope so.
