### ISSUE TITLE
Transpile only but dont-fail build and don't log errors.

### ISSUE THREAD

**Issue by sugoidesune** [nuxt/typescript#486]
**Is your feature request related to a problem? Please describe.**
I am converting a bigger project to TS and wanted to write individual components in Typescript, while leaving others in Javascript. Out of 100 components I now have one component with `<script lang="ts">`
This works seamlessly in VSCode, with typechecking and autocomplete.
The nuxt webpack build fails without `@nuxt/typescript-build` loaders, but with it Typescript throws errors for all pages and components...
I can't afford to stop development to convert everything, but would love the possibility to do so partially and benefit from typescript in VSCode.

**Describe the solution you'd like**
A simple flag that prevents the build from failing and logging errors. ( But only for typescript errors)
Something like **Next.js has:**
```js
ignoreBuildErrors: true,
```
https://nextjs.org/docs/api-reference/next.config.js/ignoring-typescript-errors

**Describe alternatives you've considered**
Additional Solution: only transpile code where `<script lang="ts">` is explicitly set.

I tried adding the flags
```js
  loaders: {
    ts: {
      silent: true,
      transpileOnly: true,
      reportFiles: []
    }
}
```

**Comment by kevinmarrec** [comment]
Hi @sugoidesune , could you provide the different error outputs you've been facing, so I can try to find a solution ? :)

**Comment by chrisvaillancourt** [comment]
Hi @kevinmarrec,

I believe I have a similar issue to @sugoidesune. It would be really helpful to have an option to successfully build for production even if there are TypeScript issues reported with ESLint. 

I created a repository showing what I mean: https://github.com/chrisvaillancourt/nuxt-typescript-fail-build

Thanks so much for your work and please let me know if I can clarify anything!

**Comment by rchl** [comment]
Looks like there already exists solution for this issue.
