### ISSUE TITLE
The type definition of `$loading` conflicts with Buefy's one

### ISSUE THREAD

**Issue by iwata** [nuxt/typescript#49]
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/iwata/codesandbox-nuxt](https://github.com/iwata/codesandbox-nuxt)

### Steps to reproduce

```sh
$ git clone git@github.com:iwata/codesandbox-nuxt.git
$ yarn install
$ yarn dev
```

### What is expected ?

No type checking errors

### What is actually happening?

It shows this error:

```
ERROR in /Users/iwata/.go/src/github.com/iwata/codesandbox-nuxt/node_modules/@nuxt/vue-app/types/index.d.ts(73,18):
TS2430: Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Property 'open' is missing in type 'NuxtLoading' but required in type '{ open: (params: LoadingConfig) => { close: () => any; }; }'.
```

### Additional comments?

If you import `Buefy` looks like `plugins/buefy.ts`, it declares `$loading` for Vue instance.
https://github.com/buefy/buefy/blob/dev/types/index.d.ts#L10
So `NuxtApp` extends the Vue, therefore `$loading` conflicts.
https://github.com/nuxt/nuxt.js/blob/v2.4.0/packages/vue-app/types/index.d.ts#L73-L74

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8559">#c8559</a>)</em></sub></div>

**Comment by ChangJoo-Park** [comment]
> > This issue still persists with element-ui
> 
> For Element-UI, the only work-around that got me out of the mess is to override Nuxt's $loading. I did this by creating a new type file in my app and defining an interface which extends NuxtApp type, where I defined the type of $loading as 'any':
> 
> In file ~/types/nuxt.d.ts
> 
> ```ts
> import { NuxtApp } from "@nuxt/vue-app/types/index";
> 
> export interface NuxtLoading extends NuxtApp {
>   $loading: any
> }
> ```

i tried `import { NuxtApp } from "@nuxt/vue-app/types/index";`
but can't find @nuxt/vue-app :sob:

**Comment by kevinmarrec** [comment]
@ChangJoo-Park 

Since new TS support, `NuxtApp` is now accessible via
```ts
import { NuxtApp } from '@nuxt/types/app/index'
```

**Comment by ChangJoo-Park** [comment]
Thanks @kevinmarrec

**Comment by dantio** [comment]
@kevinmarrec Doesn't solve my problem :/

In file ~/types/nuxt.d.ts

`
import { NuxtApp } from '@nuxt/types/app/index'

export interface NuxtLoading extends NuxtApp {
  $loading: any
}
`

nuxt: 2.9.2
element-ui: 2.4.11

Do I need to add nuxt.d.ts somewhere in tsconfig.json?

**Comment by dmix** [comment]
Has there been an issue open on ElementUI's repos about this? I'd imagine this is something they could fix although Nuxt locking down a generic global name like $loading might cause future issues. Although it's difficult to say where that line should be or not.

**Comment by dmix** [comment]
For the record the new issue on ElementUI is located here: https://github.com/ElemeFE/element/issues/17630

**Comment by JohannesLichtenberger** [comment]
BTW: Is Element-UI actively maintained or should I switch to another UI-framework? No commit since 23 days seems to be strange for such a big project!?

**Comment by kevinmarrec** [comment]
23 days seems indeed strange.

**Comment by kevinmarrec** [comment]
Has anyone found an official workaround (that may already present in this thread) that currently works ?

**Comment by JohannesLichtenberger** [comment]
In tsconfig.json:

```
"compilerOptions": {
    "skipLibCheck": true
}
```

works for me, but hmm

Maybe instead,

```
"paths": {
    "element-ui": [".sink.d.ts"] // empty file
}
```

works, too?

**Comment by dmix** [comment]
The real solution is either Nuxt or ElementUI needs to fix their namespace clashing and pick a less generic name than "loading" for root-level global stuff.

**Comment by skyrpex** [comment]
Maybe it would be worth to start thinking in terms of the composition API? If Nuxt and/or ElementUI provided this stuff through a composable there would be no problem.

For example, I'm relying on a custom made `const nuxt = useNuxtContext()` composable. I access everything related to Nuxt using that.

**Comment by dmix** [comment]
That would be ideal although legacy support for the current Vue 2 is a long term goal for the team I believe.

**Comment by skyrpex** [comment]
Yes, that's still a problem.

**Comment by kevinmarrec** [comment]
As it's a unfixable issue around the module itself, i'm closing it here. Please open an issue around Nuxt core repo (there may already be one) about changing `loading` Nuxt API for next Nuxt version.
