### ISSUE TITLE
Issue on documentation site (components page)

### ISSUE THREAD

**Issue by cdowning** [nuxt/typescript#495]
**Describe the bug**
Scripts section is not loading: https://typescript.nuxtjs.org/cookbook/components/

**To Reproduce**
1. Go to https://typescript.nuxtjs.org/cookbook/components/
2. Scroll to Scripts section

**Expected behavior**
I believe this section use to show what was needed for options api, composition api & class based api.

**Comment by cjlaborde** [comment]
Have same issue for days
![image](https://user-images.githubusercontent.com/40572114/111034295-574ab880-83eb-11eb-8bc2-60bfe2238db6.png)

As well this link is dead the one to edit the docs.
https://github.com/nuxt/typescript/edit/main/docs/content/en/cookbook/components.md

**Comment by cjlaborde** [comment]
This is how it should look like, these screenshot from youtube video.
![image](https://user-images.githubusercontent.com/40572114/111041080-d7354a80-840c-11eb-95ab-e077220acb4c.png)
![image](https://user-images.githubusercontent.com/40572114/111041096-f2a05580-840c-11eb-9871-72ede163acfc.png)
![image](https://user-images.githubusercontent.com/40572114/111041101-021f9e80-840d-11eb-92e5-f5282544255e.png)
![image](https://user-images.githubusercontent.com/40572114/111041115-0f3c8d80-840d-11eb-8c5f-f20800d8ce8f.png)

**Comment by rchl** [comment]
Appears to be working fine now.

![Screenshot 2023-03-13 at 21 51 07](https://user-images.githubusercontent.com/153197/224829327-5990f077-0777-4871-b36b-4638cc328b39.png)

**Comment by rchl** [comment]
Actually this might still be broken in some cases but there is https://github.com/nuxt/typescript/issues/514 with working reproduction.
