### ISSUE TITLE
TS2339: Property 'strategy' does not exist on type 'Auth<any>'

### ISSUE THREAD

**Issue by vajihemrp** [nuxt/typescript#499]
User have logged in successfully throw this.$auth.loginWith('laravelPassportPassword')  in nuxtjs with typescript using nuxt/auth module.
[https://auth.nuxtjs.org/](url)

Then I tried to get token with this.$auth.strategy.token.get() method. It shows the following error:

`
TS2339:Property 'strategy' does not exist on type 'Auth<any>'.

                })
               .then(() => {
               console.log({ token: this.$auth.strategy.token.get() })
                                               ^^^^^^^^   
               this.$router.push('/')
           })

`

**Versions**

- @nuxt/cli : "v2.13.3"
- nuxtjs/auth-next: "v5"
- ts: "v4.2"
- node: v14.15.1

**Comment by kevinmarrec** [comment]
zda
dzadza
dza
zda
dzadza
dza

**Comment by kevinmarrec** [comment]
dzadzaz
dzadzaz
dzadzaz
dzadzaz
dzadzaz
dzadzaz
dzadzaz
dzadzaz
dzadzaz

**Comment by kevinmarrec** [comment]
Hi @vajihemrp , this seems tor be an issue with `nuxtjs/auth-next` typings.

`strategy` may be something that can be accessed on `$auth` but if the type of `$auth` is not right, then you'll have this error.

Consider opening an issue on https://github.com/nuxt-community/auth-module
