### ISSUE TITLE
Make production-ready SSR nuxt app without runtime-transpiling

### ISSUE THREAD

**Issue by Sletheren** [nuxt/typescript#502]
**Describe the bug**
I have a Nuxt JS project using SSR and `nuxt-ts`
I am trying to achieve a production ready build to integrate with my CI/CD,
Now when I run `nuxt-ts build` I am assuming that whatever the content of `.nuxt/dist` can be copied somewhere and run using `node .nuxt/dist/server/server.js` or something?  but instead I have to run `nuxt-ts start` which seems to do transpilation on run-time.

Is there a way to build and have the artifacts ready to run on a node environment? without needing typescript transpiration again?

My`nuxt.config.js` looks like follows:

```
export default {
  ssr: true,
  target: 'server',
  srcDir: 'src/',
  buildModules: [
    // https://go.nuxtjs.dev/typescript
    '@nuxt/typescript-build',
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
  ],

  server: {
    port: envsConfig.env.HTTP_PORT || 2055,
  }
}
```
And my scripts look like:

```
"scripts": {
    "dev": "nuxt-ts",
    "build": "nuxt-ts build",
    "build:prod": "NODE_ENV=production nuxt-ts build",
    "start": "nuxt-ts start",
    "start:prod": "NODE_ENV=production nuxt-ts start",
}

```

Any help would be appreciated! thanks

**Comment by danielroe** [comment]
It's likely that you no longer need `@nuxt/typescript-runtime`. (Looking at your `nuxt.config`, I'm not sure you did before, either.) Just try replacing `nuxt-ts` with `nuxt` and see if it works.

**Comment by Sletheren** [comment]
you're right, no need for @nuxt/typescript-runtime, and had to change the start and build to use `nuxt` instead!
Cheers and thanks!
