### ISSUE TITLE
Move typescript to peerDependencies

### ISSUE THREAD

**Issue by negezor** [nuxt/typescript#512]
**Is your feature request related to a problem? Please describe.**
For codebases that use the monorepo approach, there are many problems with upgrading to a new version of TypeScript. Updates for this package are rolled out mostly just to bump the package version in dependencies.

**Describe the solution you'd like**
Move `typescript` to `peerDependencies`

**Describe alternatives you've considered**
Update the package more often :)

**Additional context**
At the moment, the package only supports the 4.2 version of TypeScript, and 4.3 was released two months ago

**Comment by negezor** [comment]
Any updates? TypeScript 4.4 is released.

**Comment by maninak** [comment]
[Typescript v4.5 is released](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/) and we're stuck at v4.2.4 :(

**Comment by negezor** [comment]
@maninak one solution is to switch to [@nuxt/bridge](https://v3.nuxtjs.org/getting-started/bridge)

**Comment by maninak** [comment]
Not possible right now, sadly (I've tried it twice). Something isn't playing along and I don't know what. Probably some of our nuxt plug-ins. I'm reducing our dependencies every week, targeting nuxt-bridge.

**Comment by homerjam** [comment]
Hmm, any chance we can get an updated typescript dependency? 😁
