### ISSUE TITLE
Vue property decorator. Custom link with v-text and NuxtLink not work. Typescript

### ISSUE THREAD

**Issue by n4an** [nuxt/typescript#523]
`< template >
< div >
  < internal-link
    :to="localePath(uri)"
    itemprop="name"
    v-text="text"
  / >
< /div >
< /template >`

Other component

`< template>
  < div>
    < NuxtLink
      :to="to"
      exact
    >
      < slot name="default" / >
    < /NuxtLink>
  < /div>
< /template>

< script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component
export default class InternalLink extends Vue {
  @Prop({ default: '#' })
  to: Object|String
}
< /script>`

And the result is   `< div itemprop="name">Home< /div>`    and not    `< div itemprop="name"><a href="home">Home< /a>< /div>`

**Comment by rchl** [comment]
Please create proper reproduction if you are still having this issue.

Expecting us to manually re-assemble your on purpose broken code is a bit too much to ask.

(You can put your code between three backtics on github to have it rendered in plain text)
