### ISSUE TITLE
Doing type checking in CI

### ISSUE THREAD

**Issue by CapitaineToinon** [nuxt/typescript#531]
**Is your feature request related to a problem? Please describe.**
Sorry if this isn't directly related to nuxt/typescript but I'm not sure how to resolve this issue or where to ask. Here the context.

Somehow, a developer managed to push some code that didn't compile (accessing variables in `this` that didn't exists, returning the wrong type in a function) but was still valid JavaScript. We currently have have eslint and prettier setup in CI but none of those are capable of doing type checking.

**Describe the solution you'd like**
It would be great to have a cli available to check this.

**Describe alternatives you've considered**
Apparently it's possible to do typecheking by running `tcs --noEmit` but out of the box it doesn't work with a nuxt project and I have no idea how to make it work. Would love some help on the matters or links about the subject. I couldn't find anything specific to nuxt. 

**Additional context**
Here's an example where eslint finds that the test variable isn't used but fails to find all the typescript errors, which is normal as far as I know. How can I find these errors in CI?
![](https://cdn.discordapp.com/attachments/856705268829257728/904795577672413274/unknown.png)

**Comment by maninak** [comment]
If I understand correctly, you want your build to fail if there are TS errors. Perhaps the flag [`--fail-on-error`](https://nuxtjs.org/docs/get-started/commands/#fail-on-error) will do it for you if you append it to your `nuxt generate` or `nuxt build` scripts.

**Comment by rchl** [comment]
I'm assuming that `--fail-on-error` flag answers the question.

Personally I see here that `nuxt build` fails here even without this flag when there are type errors. At least in Nuxt 2.16.3.
