### ISSUE TITLE
TS2352 after yarn upgrade, what happened?

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/typescript#532]
**Describe the bug**
After running a yarn upgrade ("lock file maintenance"), my build throws many `TS2352` errors.

**To Reproduce**
https://github.com/maevsi/maevsi/runs/4211805080?check_suite_focus=true

**Expected behavior**
No breaking changes in minor version updates in related dependencies.

**Additional context**
I know that this issue most likely doesn't originate from this repo's code itself, but this seems like the most appropriate place for nuxt users to start searching for a solution.

**Comment by rchl** [comment]
Is this still relevant? Do you know a way to reproduce it?

**Comment by dargmuesli** [comment]
I don't think so.
