### ISSUE TITLE
Don't know how to set the option

### ISSUE THREAD

**Issue by highhi** [nuxt/typescript#536]
I would like to enable transpileOnly, but I don't know how to set it up. Where should I put this in `nuxt.config`?

```
loaders: {
  ts: {
     transpileOnly: true,
     appendTsSuffixTo: [/\.vue$/],
   },
},
```
https://typescript.nuxtjs.org/ja/guide/setup#loaders

nuxt: v2.15.8
@nuxt/typescript-build: v2.1.0

**Comment by rchl** [comment]
It's a module configuration option. See #579 for how it should look until documentation is updated.
