### ISSUE TITLE
TS Support for Nuxt 2 fate

### ISSUE THREAD

**Issue by Milkywayrules** [nuxt/typescript#541]
Hi!

I didn't find the Discussions column so I will ask a question regarding the future of TS for Nuxt 2 here, in Issues.

While Nuxt 3 is still on going on the development process and still on the beta stage, I a little bit worry of this support. It's almost a year without any update and there are couples of PR and issues abandoned.

Is this on purpose because we prepare something big (on Nuxt 3)? I still use this support for my product and some people's projects still using this TS Support.

Thank you 😁

**Comment by BuddhiAbeyratneAL** [comment]
Did you ever get an answer on other methods ? 

re #546

**Comment by rchl** [comment]
The typescript dependency was now updated (or made a peer dependency rather) in #563 and will be released in next version.

Don't think there is anything else to address here.
