### ISSUE TITLE
Class API Support

### ISSUE THREAD

**Issue by BuddhiAbeyratneAL** [nuxt/typescript#546]
Im a person who loves the Class api of Nuxt ts its easy to structure components for me personally while using it. I'm sad to see it go away but I don't want to see others going through the migration hell I'm looking forward to. 

**Is your feature request related to a problem? Please describe.**
Class API is still a recommended option on Nuxt documentation. ?
Will Vue3 support come to Nuxt ts ?
will class api be continued ? 
Is there a recommended path for the community to use to migrate out if not ?

**Describe the solution you'd like**
Appropriate warnings if possibility of discontinuation exists

**Describe alternatives you've considered**
Continue to support class api 

By all means I do not want the class api to die. I truly wish people used it more. 
I just want people to know if It's being killed off without it being called a "Soft release".
It helps to encourage appropriate hiring and tech stack choices for larger teams who rely on Nuxt ts to mitigate an eminent version migration hell if it's to be the case.

**Comment by rchl** [comment]
This is not really a place for asking such questions. This module merely uses the package that is maintained by Vuejs organization at https://github.com/vuejs/vue-class-component#readme. We don't have control over what happens with it.
