### ISSUE TITLE
ts-loader dependency error in typescript example.

### ISSUE THREAD

**Issue by Curstantine** [nuxt/typescript#549]
**Describe the bug**
Demo project is requesting `ts-loader` dependency but installing it doesn't fix it.
From what I understand `@nuxt/typescript-build` should handle it.

**To Reproduce**
1. `yarn create nuxt-app app`
2. Choose typescript option
3. `yarn run dev`

**Expected behavior**
For it to show the example page without throwing errors.

**Screenshots**
![Screenshot_20220504_124433](https://user-images.githubusercontent.com/69104500/166637106-226a1623-db13-4324-ae6c-c5b83d4ef7cd.png)

![Screenshot_20220504_124559](https://user-images.githubusercontent.com/69104500/166637242-aadbc8ad-c95b-4449-bb1d-00a7ccc0cad7.png)

**Additional context**
Installing ts-loader as a dev-dep doesn't fix the problem.

**Comment by rchl** [comment]
I can't quite reproduce this issue on newly created nuxt 2 app.
Probably it got fixed at some point.
Feel free to comment if you still have this issue.
