### ISSUE TITLE
How to use addTemplate API by typescript

### ISSUE THREAD

**Issue by Liuyicong-git** [nuxt/typescript#552]
In my nuxt module , I use addTemplate API ,
`
  this.moduleContainer.addTemplate({
      src: path.join(oldFolderName , file),
      fileName: path.join(newFolderName , file ) 
  })       // result : the file postion result  at :    ./nuxt/newFolderName/test.js    
`
but in my plugin file , import template is Error . 
my way like : import  test from ""./newFolderName/test.js" (use typescript is Error ,  while not use typescript is Ok), how i use typescript way import this file

**Comment by rchl** [comment]
Feel free to provide more info. Ideally a repo that reproduces this issue.
Otherwise there is not much we can do to help.
