### ISSUE TITLE
Outdated typescript dependency

### ISSUE THREAD

**Issue by rchl** [nuxt/typescript#557]
**Describe the bug**
This package has `typescript` dependency pinned to `~4.2` which causes issues in projects that require new version of typescript. Installing later version of typescript in the project causes various weird errors due to two versions of `typescript` being present in the project. What's the reason for pinning old version?

**To Reproduce**
The issue can be reproduced on the https://github.com/rchl/lsp-log-parser/ project after removing `resolutions` from `package.json`.

**Expected behavior**
No errors after installing new version of `typescript` in the project
or
don't pin old version of typescript in dependencies

**Additional context**
This issue can be worked around by using yarn `resolutions`.

**Comment by kevinmarrec** [comment]
Pinned minor version was due to various type errors encountered cause of some Vue types with oldest Typescript versions, but I guess it's pretty safe to bump it to latest.

I didn't plan any updates soon so I'd stick with `resolutions` as it's straight forwars workaround.

I may update it later on.

**Comment by rchl** [comment]
`resolutions` is a workaround and also not even currently documented so that means that people will either not figure it out themselves or have to spend a good amount of time figuring it out.

Also, not sure what would be the workaround with `npm` since it doesn't support `resolutions`.

**Comment by homerjam** [comment]
@rchl Could you please show how you worked around the issue with `resolutions`? I'm having trouble!

**Comment by rchl** [comment]
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by rchl** [comment]
@kevinmarrec why are you insisting on keeping old version pinned? Having such an old version in the project causes type issues.

**Comment by rchl** [comment]
If you are still not planning to update it then I'll probably have to create a fork and publish as a separate pacakge.

(And please don't suggest using bridge instead since it's a can of works in Nuxt 2)
