### ISSUE TITLE
Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by Rain-Hsiang** [nuxt/typescript#561]
**Describe the bug**
`Cannot read properties of undefined (reading 'options')！`

**To Reproduce**
*1*. get [nuxt3](https://nuxt.com/docs/getting-started/installation) demo
```
npx nuxi init <project-name>
yarn
```
*2*. add [@nuxt/typescript-build](https://typescript.nuxtjs.org/zh-hant/guide/setup/)
```
yarn add --dev @nuxt/typescript-build @nuxt/types
```
nuxt.config.ts
```ts
export default defineNuxtConfig({
  modules: ['@nuxt/typescript-build'],
});
```
tsconfig.json
```json
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ESNext", "ESNext.AsyncIterable", "DOM"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@types/node", "@nuxt/types"]
  },
  "exclude": ["node_modules"]
}
```

**Expected behavior**
no error

**Screenshots**
<img width="817" alt="截屏2023-02-28 13 23 09" src="https://user-images.githubusercontent.com/125465912/221761701-3e0b15be-3ba8-4924-8713-e41846ab3d64.png">

**Additional context**

**Comment by danielroe** [comment]
This module is not compatible (or needed) with Nuxt 3. Nuxt 3 has TypeScript support built in.

**Comment by Rain-Hsiang** [comment]
> This module is not compatible (or needed) with Nuxt 3. Nuxt 3 has TypeScript support built in.

thanks
