### ISSUE TITLE
vscode ****.json file  Point out error: "Expected an assignment or function call and instead saw an expression"

### ISSUE THREAD

**Issue by Rain-Hsiang** [nuxt/typescript#562]
**Describe the bug**
<img width="1307" alt="截屏2023-03-07 19 26 06" src="https://user-images.githubusercontent.com/125465912/223435228-6d4472ab-715b-4eea-baa3-0780408d4c78.png">

**To Reproduce**
1.[nuxt3 demo](https://nuxt.com/docs/getting-started/installation)
 `pnpm dlx nuxi init <project-name>`
`pnpm i`

2.[eslint](https://typescript.nuxtjs.org/zh-hant/guide/lint/) 
`pnpm i -D @nuxtjs/eslint-config-typescript eslint typescript`

3.dispose  vscode 'eslint.validate'
<img width="1023" alt="截屏2023-03-07 19 28 09" src="https://user-images.githubusercontent.com/125465912/223437687-7174ac88-09ef-4e17-ad77-ede67d1663a4.png">
<img width="1137" alt="截屏2023-03-07 19 27 00" src="https://user-images.githubusercontent.com/125465912/223437696-4d176e2a-c9db-4ebd-924e-c29bd1722027.png">

**Expected behavior**
no  error

**demo**
[https://gitee.com/rain-f2e/demo](https://gitee.com/rain-f2e/demo)

**Comment by rchl** [comment]
I don't think you are supposed to use this project with Nuxt 3.

**Comment by Rain-Hsiang** [comment]
> I don't think you are supposed to use this project with Nuxt 3.

...ok
thank you
