### ISSUE TITLE
Use nuxt-property-decorator instead vue-property-decorator in examples

### ISSUE THREAD

**Issue by SyloRei** [nuxt/typescript#58]
**Is your feature request related to a problem? Please describe.**
In the class-api examples, the vue-property-decorator library was used. But this library does not contain all the parameters of the nuxt components.

**Describe the solution you'd like**
Use nuxt-property-decorator in examples.  It is clearer for nuxt.

**Comment by NickBolles** [comment]
I'm pretty sure nuxt-property-decorator doesn't have any benefits over vue-property-decorator. Nuxt registers the hooks, which is essentially all that nuxt-property-decorator does, and re-exports everything from vue-property-decorator.

**Comment by SyloRei** [comment]
> I'm pretty sure nuxt-property-decorator doesn't have any benefits over vue-property-decorator. Nuxt registers the hooks, which is essentially all that nuxt-property-decorator does, and re-exports everything from vue-property-decorator.

You are right, but when the application grows out of the current example / template and requires, for example, fetch or asyncData hook, the user of this example will be confused. Maybe he does not know about nuxt-property-decorator library.

**Comment by kevinmarrec** [comment]
@SyloRei Basic & Avanced examples that will be available [here](https://typescript.nuxtjs.org/examples/object-api/minimal.html) will showcase the use of `fetch` and `asyncData` around the component options.

Something you might not be aware is that `layout` for example can be either a `string` or `function`, and when you want it to be a string, defining a property `layout` won't work, you'll need to give it to the component options. And I think this behavior is more likely to happen and bring more confusion than not talking about `nuxt-property-decorator` in first instance.

Furthermore, `nuxt-property-decorator` being, as said @NickBolles , kind of wrapper as it re-export everything and just register hooks.

**Comment by SyloRei** [comment]
I agree, let's close
