### ISSUE TITLE
@nuxt/typescript-build‘s dependencies with typescript@4.2 is too low 

### ISSUE THREAD

**Issue by allenchannn** [nuxt/typescript#616]
**Describe the bug**
i use pnpm to install nuxt and use "useUnknownInCatchVariables" options in tsconfig.json. But there is something wrong like this:

**To Reproduce**
1. Clone repository '...'
2. Run '....'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rchl** [comment]
Latest version includes TS 5.x as a peer dependency. Maybe you are not using the latest version.
