### ISSUE TITLE
ts-loader options.

### ISSUE THREAD

**Issue by steven0811** [nuxt/typescript#76]
I'm using express + nuxt with full stack Typescript.

In tsconfig.json  I must set `compilerOptions` -> `module` to `"commonjs"` , In this case express will working properly, but not fit for nuxt.

Before nuxt < 2.8.x,  I will override ts-loader options in nuxt.config.ts `build.loaders.ts.compilerOptions` or `build.loaders.ts.configFile` to use different typescript rules.

But now I migrated Nuxt from 2.8.x to 2.9.x, follow [https://typescript.nuxtjs.org/migration.html](url) instruction, As mentioned previously way is not working anymore (because typescript-build is way behind default settings?).

So I checked that typescript-build module, no any options can pass to ts-loader.

This is my modify version:
ex.
nuxt.config.ts
```js
typescript: {
    typeCheck: true,
    loaderOptions: {
      compileOptions: {
             target: "esnext",
             module: "commonjs"
      }
    }
  },
```

ex.
typescript-build/lib/module.js
```js
config.module.rules.push(...['ts', 'tsx'].map(ext =>
      ({
        test: new RegExp(`\\.${ext}$`, 'i'),
        use: [
          babelLoader,
          {
            loader: 'ts-loader',
            ...Object.assign({}, {
              transpileOnly: true,
              [`append${ext.charAt(0).toUpperCase() + ext.slice(1)}SuffixTo`]: [/\.vue$/]
            }, loaderOptions)
          }
        ]
      })
    ))

```

Or any better way can do?

**Comment by kevinmarrec** [comment]
Indeed, in Nuxt 2.8.x , the `ts` & `tsx` loaders (`build.loaders.x`) were registered in core, so the options could be customizable through configuration file, it's indeed not possible anymore.

So yes you're right, the module should provide options to customize them.
Not only `ts` loader but also `tsx` one.

I'll take care having this feature available as soon as possible (within next 6 hours).

**Comment by steven0811** [comment]
Great!!! thank you.

**Comment by kevinmarrec** [comment]
@steven0811 Could you quick check https://github.com/nuxt/typescript/pull/93 ?
