### ISSUE TITLE
Alias "@" not recognized by typescript loader

### ISSUE THREAD

**Issue by edimitchel** [nuxt/typescript#79]
**Describe the bug**
When I wish to import components from my source folder using alias `@`, TypeScript checker returns me an error in logs. Also, code runs properly.

**To Reproduce**
Run https://codesandbox.io/s/issue-alias-nuxt-typescript-o5wzk

**Expected behavior**
No error in console. TypeScript loader have to retrieve the way to get the right folder (in the codesandbox case, it's on the root folder).

**Screenshots**
![image](https://user-images.githubusercontent.com/2922851/63522817-51d00980-c4f9-11e9-8f50-8e17e018558a.png)

**Comment by Cy-Tek** [comment]
Hi, I was having the same issue, but I had forgotten to put this in my nuxt.config file
`buildModules: ['@nuxt/typescript-build']`, can you confirm that you have it in yours?

**Comment by edimitchel** [comment]
> Hi, I was having the same issue, but I had forgotten to put this in my nuxt.config file
> `buildModules: ['@nuxt/typescript-build']`, can you confirm that you have it in yours?

Please take a look to the codesandbox project, I have test with `modules `and `buildModules`.. and both are not working well.

**Comment by zipme** [comment]
It seems it's working if you don't skip the file extension, so `import Test from "@/components/test.vue"`

**Comment by edimitchel** [comment]
Thanks @zipme you're a right for my example, but for my local repo, it doesn't fix that.
After comparing `tsconfig.json` file, I see that I have a difference on paths...

```diff json
    "paths": {
-      "~/*": ["/*"],
-      "@/*": ["/*"]
+      "~/*": ["./*"],
+      "@/*": ["./*"]
    },
```

So now, it working as expected ! Sorry for this issue !
