### ISSUE TITLE
It doesn't work with nuxt.js v2.9.0 + typescript + vuetify.

### ISSUE THREAD

**Issue by paveg** [nuxt/typescript#85]
### Version

[v2.9.0](https://github.com/nuxt.js/releases/tag/v2.9.0)

```shell
$ yarn -v
1.17.3
$ node -v
v12.7.0
```

### Reproduction link

[https://github.com/paveg/pwa-portfolio/pull/24](https://github.com/paveg/pwa-portfolio/pull/24)

### Steps to reproduce

I think the following steps should reproduce it.

```shell
$ check out to this PR.
$ yarn && yarn build
```

### What is expected ?

I executed command `yarn build` , it was failed.
( The actual command called is `nuxt build` )
I migrated as a [migration guide](https://typescript.nuxtjs.org/migration.html), but the build fails.

### What is actually happening?

Nuxt build error has occurred.
[GitHub CI/CD logs](https://github.com/paveg/pwa-portfolio/pull/24/checks?check_run_id=202328079#step:6:29)

```shell
ERROR in ./components/helper/Offset.vue?vue&type=script&lang=ts& (./node_modules/vue-loader/lib??vue-loader-options!./components/helper/Offset.vue?vue&type=script&lang=ts&) 22:13
Module parse failed: Unexpected token (22:13)
File was processed with these loaders:
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   },
|   computed: {
>     classes(): any {
|       return {
|         "v-offset--full-width": this.fullWidth
 @ ./components/helper/Offset.vue?vue&type=script&lang=ts& 1:0-121 1:137-140 1:142-260 1:142-260
 @ ./components/helper/Offset.vue
 @ ./node_modules/vue-loader/lib??vue-loader-options!./pages/privacy_policy/index.vue?vue&type=script&lang=ts&
 @ ./pages/privacy_policy/index.vue?vue&type=script&lang=ts&
 @ ./pages/privacy_policy/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error


  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5302:21)
  at processTicksAndRejections (internal/process/task_queues.js:85:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5252:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5590:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:95:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2563:7)
```

### Additional comments?

If there is something wrong, I would be happy if you could point it out.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9679">#c9679</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@paveg Indeed if you're using `nuxt.config.ts` you need `@nuxt/typescript-runtime`.
It's mentionned in the migraiton guide :
> If your project is using TypeScript runtime (**nuxt.config.ts**, local **modules** or **serverMiddlewares**), please directly refers to the [Runtime](https://typescript.nuxtjs.org/guide/runtime.html#installation) section.

Without the runtime support, Nuxt will skip `nuxt.config.ts` and load a default `nuxt.config.js`. So your whole configuration is skipped, including `@nuxt/typescript-build` module that register the loaders that handles TypeScript in components.

That's why you have "You may need an additional loader to handle the result of these loaders" errors.

**Comment by paveg** [comment]
@kevinmarrec @aldarund 
Thanks for replying.
I confirmed build succeed when use typescript-runtime and `nuxt-js` commands.

This issue has been resolved.


Nuxt.js is good framework and its' community is cool 🚀.
