### ISSUE TITLE
[Documentation] Missing open graph metadata

### ISSUE THREAD

**Issue by eladcandroid** [nuxt/typescript#88]
Facebook sharing debugger result:

(https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftypescript.nuxtjs.org%2F)

<img width="1045" alt="Screen Shot 2019-08-27 at 9 51 41" src="https://user-images.githubusercontent.com/13297000/63747705-71c44c00-c8b0-11e9-9ecd-2b5632f49864.png">

**Comment by kevinmarrec** [comment]
@eladcandroid Thanks for pointing this, I think I need to customize some options of Vuepress so it correctly provide open graph metadata.

**Comment by kevinmarrec** [comment]
https://github.com/webmasterish/vuepress-plugin-autometa may be relevant to use
