### ISSUE TITLE
I can't read _**this.$store.state**_ when I run with `ts-node server/index.ts`

### ISSUE THREAD

**Issue by Him-2C** [nuxt/typescript#92]
**Describe the bug**
I can't read _**this.$store.state**_ when I run with `ts-node server/index.ts`
but I can when I run with `yarn nuxt-ts`

I checked it inside _**.nuxt**_

This image with `ts-node server/index.ts`

![image](https://user-images.githubusercontent.com/30730045/63947723-a9461a80-caa1-11e9-89e9-114ac6eb7d0c.png)

this image with `yarn nuxt-ts`

![image](https://user-images.githubusercontent.com/30730045/63947875-ee6a4c80-caa1-11e9-85ba-53c1bb4b0b33.png)

**Comment by kevinmarrec** [comment]
@Him-2C From which file did you screenshot these images ?

**Comment by Him-2C** [comment]
.nuxt/store.js

**Comment by kevinmarrec** [comment]
I think you need further configuration for store when using Nuxt programatically.
Do you have any repository with reproduction ? Is it a type error or the state is undefined ?

**Comment by Him-2C** [comment]
state is undefined

**Comment by Him-2C** [comment]
I will push CodeSandbox please wait me.

**Comment by kevinmarrec** [comment]
@Him-2C See :
https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/store.js#L10
which leads to
https://github.com/nuxt/nuxt.js/blob/dev/packages/builder/src/builder.js#L399

I think you're missing telling in Nuxt config where the `store` dir is located.

**Comment by kevinmarrec** [comment]
@Him-2C I'm not sure CodeSandbox will work with Nuxt Programatically

**Comment by Him-2C** [comment]
https://github.com/Him-2C/nuxt-express-check-store

please check `yarn run:dev` vs `yarn dev`

**Comment by kevinmarrec** [comment]
@Him-2C Fixed it by adding that: 
```js
await nuxt.moduleContainer.ready()
```
just after https://github.com/Him-2C/nuxt-express-check-store/blob/master/server/index.ts#L11

This is something not documented in Programatically usage, but this need to be called so that modules are registered.

**Comment by Him-2C** [comment]
Thank man is work!

**Comment by Him-2C** [comment]
So perfect like this.

![image](https://user-images.githubusercontent.com/30730045/63962686-8164b000-cabd-11e9-8470-bc286ffdfe2d.png)

**Comment by shalldie** [comment]
I met this problem too,

i see `await nuxt.ready()` at [release notes](https://nuxtjs.org/guide/release-notes#programmatic-api-middleware), but there is no description in programmatically.

Should it be documented? Or will it be changed in the feature.
